### ISSUE TITLE
[Bug]: Status bar remains visible in "Card" mode

### ISSUE THREAD

**Issue by Quintus19** [chr56/Phonograph_Plus#101]
### Bug Summary

The status bar should be transparent in the Card view but it isn't. Album cover renders in the invisible area which makes the cover look cropped.

### Version

0.8-dev3

### Steps to reproduce the bug

Play a song with "Card" view active.

### Screenshots or Screen recordings

![ppp_suggest](https://github.com/chr56/Phonograph_Plus/assets/119014876/990970cf-2c09-4fe2-8c59-97974f5a2b65)

**Comment by chr56** [comment]
Confirmed

**Comment by chr56** [comment]
Fixed after 778d27d3108aa471c9e8a99fe78e851e806b8951

**Comment by chr56** [comment]
[v1.1.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.1.0) released! Close!
