### ISSUE TITLE
[Bug] playback controls not working via some Bluetooth device

### ISSUE THREAD

**Issue by DemonoidMaster** [chr56/Phonograph_Plus#104]
### Bug Summary

Issue: currently i cannot use my headset (bluetooth) media controls
• Vol+ when held normally skips playing track, this doesn't work anymore. (Vol up when pressed once, this button action works.)
• Vol- when held restarts the song (Vol down when pressed once, this button action works.) and if held again skips back a song, this doesn't work anymore
• Play/pause button doesn't work anymore

This started with this version 1.0.0 (just tested v0.7.2.3 LTS and it works as intented, currently regressed back to that version for now until this bug is fixed) tried clearing app data, same result, tried VLC as a test and it works so my headset isn't faulty.

I think this bug might have to do with the new feature "playback speed control" or maybe "scrollbar for playing queue", could be something else entirely i don't know.

### Version

1.0.0

### Steps to reproduce the bug

Using a bluetooth headset like mine (Anker Soundcore Life Q20)

### Environment

CherishOS 3.9 (Android 12L)

[Yes i know i haven't updated my rom when theres newer versions, but I'm tired of devs deciding to change stuff that makes updates clean flash only every other week, so for now I'm not going to bother with it because migrating my stuff is a pain in the ass including having to set everything up again]

**Comment by chr56** [comment]
Already fixed in [v1.0.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.1).

**Comment by DemonoidMaster** [comment]
Yes i know i am the person who had reported this to you (and tested your test build fix) on telegram

So far so good with 1.0.1👍, haven't had issues since
