### ISSUE TITLE
[Bug]: Missing Thumbnails

### ISSUE THREAD

**Issue by alphanerdgen** [chr56/Phonograph_Plus#105]
### Bug Summary

The app is not showing the thumbnail album art in the album row within an artist's tile. This is happening even with artist's with one album. See attached screenshot.

### Version

1.0.0

### Steps to reproduce the bug

1. Tap on any artist's tile.
2. Notice the album row which doesn't display the respective album art.

### Screenshots or Screen recordings

![Screenshot_Phonograph Plus](https://github.com/chr56/Phonograph_Plus/assets/83120103/eb2cb8c5-3637-4c92-ba2e-86315b1b39bc)

### Environment

Android 12

**Comment by chr56** [comment]
Confirmed.

**Comment by chr56** [comment]
Fixed in [v1.0.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.2). Close!
