### ISSUE TITLE
[Bug]: Tag Editor Causing the App to Behave Weirdly

### ISSUE THREAD

**Issue by alphanerdgen** [chr56/Phonograph_Plus#106]
### Bug Summary

The app becomes unusable after tapping on the 'Tag Editor' under the 'More' section. Although the track continues to play in the background, the playback controls in the notification tray also become unusable. In one instance, the app even crashed. Sorry, I couldn't copy the crash report.

### Version

1.0.0

### Steps to reproduce the bug

1. Tap on the three-dots on the right-hand side of a track.
2. Tap on More.
3. Tap on Tag Editor.

### Screenshots or Screen recordings

Screen becomes grey the moment I tap on 'Tag Editor':

![Screenshot_Phonograph Plus_G1](https://github.com/chr56/Phonograph_Plus/assets/83120103/24b62f16-99d7-4720-b691-bfee12223c4f)

In the Recent Apps Menu, too:

![Screenshot_Phonograph Plus_G2](https://github.com/chr56/Phonograph_Plus/assets/83120103/89403c9c-c4a8-4315-ba63-2fb9f45e26ca)

### Environment

Android 12.

### Other helpful information

Downloaded from F-Droid.

**Comment by chr56** [comment]
Is this permanently frozen?

**Comment by alphanerdgen** [comment]
@chr56 Until I 'force stop' the app. But after updating the app to version 1.0.1 from F-Droid a few minutes ago, this issue isn't there anymore. Hurray!

Closing this.
