### ISSUE TITLE
Remove Unnecessary Information to Improve UI

### ISSUE THREAD

**Issue by alphanerdgen** [chr56/Phonograph_Plus#107]
Please see the screenshot.
 
![Screenshot_PP_Track Nos](https://github.com/chr56/Phonograph_Plus/assets/83120103/75de523e-9bff-4792-bc6f-d28de1be1444)

I don't think that showing the total track numbers over there alongside the name of the album is very helpful. All it does is clutter that small space. A user can get that info after opening an album anyway.

![Screenshot_PP_1](https://github.com/chr56/Phonograph_Plus/assets/83120103/ec61a96b-aa7c-4267-8215-fda91440d8fb)

Version: 1.0.0

**Comment by chr56** [comment]
I see.

**Comment by chr56** [comment]
#107 and #105 are bugs introduced in v1.0.0 due to lack of test after changing the horizonal albums' ui.

**Comment by chr56** [comment]
Fixed in [v1.0.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.2). Close!
