### ISSUE TITLE
Android Auto: App not showing up in launcher settings

### ISSUE THREAD

**Issue by stuffi3000** [chr56/Phonograph_Plus#109]
### Bug Summary

Hi,
First of all, thank you very much for your work on this app! It's really great. I've moved to this app from Vinyl since that one wasn't actively developed anymore.

Now, for the bug: You recently added support for Android Auto, which I was really looking forward to. However, after installing the latest dev/preview version I still couldn't find the app in my Android Auto launcher settings...

I'm not sure if this is a bug or whether it's on my end. I have a Samsung Galaxy A40, running Android 11 and the latest Samsung firmware. 

### Version

1.1-dev2

### Steps to reproduce the bug

1. Install latest version
2. Go to Android Auto settings
3. Click on "Setup launcher" button
4. Find that Phonograph Plus Preview is not in the list. 

### Screenshots or Screen recordings

![Screenshot_20230818-105531_Android Auto](https://github.com/chr56/Phonograph_Plus/assets/11315157/93d3e58f-48f7-490d-a9b1-14b000c03f66)
![Screenshot_20230818-105534_Android Auto](https://github.com/chr56/Phonograph_Plus/assets/11315157/67bcc359-d1e8-4b69-bb12-0e96ed012fa5)

### Environment

Samsung Galaxy A40
Android 11
Stock Samsung ROM with OneUI 3.1

**Comment by chr56** [comment]
Sorry, I am not sure what the problem is. Auto obviously doesn't detect this as an automotive application successfully.
This is very tricky, because I have no idea how to fix this.

_It might take days or months, or even years (~Phonograph Plus might not get there~) to get the problem fixed._

**Comment by chr56** [comment]
Can you provide more information please? @stuffi3000 
Go to Android Auto application (the upper level of your screenshots), click `version`: copy all text.

**Comment by stuffi3000** [comment]
@chr56 
Pakete:
WhatsApp: 2.23.16.76
Maps: 10.80.0
Teams: 1416/1.0.0.2023084001
Google Play Store: 37.0.22-29 [0] [PR] 555741925
Nachrichten: 12.2.20.151
Waze: 4.96.1.0
Google Play-Dienste: 23.30.13 (150400-552628474)
Phonograph Plus Preview: 1.1-dev2
Google: 14.32.17.28.arm64
YouTube Music ReVanced Extended: 6.13.52
Android Auto: 10.1.633034-release
OsmAnd+: 4.1.11
Messenger: 422.0.0.18.107
Discord: 190.17 - Stable

Berechtigungen:
phone: an
contacts: an
location: an
sms: an
microphone: an
calendar: aus
call_log: an
nearby_devices: aus

**Comment by chr56** [comment]
Thank you!
It detected.

**Comment by chr56** [comment]
Wait a moment.
Can you enter the `Developer Mode of Auto`? 
- Click Android Auto's `version` multiple times to enter Developer Mode.
- Go to Developer Settings in menu
- click the second last one: `Unknown Source`
- Check again

**Comment by stuffi3000** [comment]
> Wait a moment.
> Can you enter the `Developer Mode` of Auto? 
> - Click Android Auto's `version` multiple times to enter Developer Mode.
> - Go to Developer Settings in menu
> - Click the second last one: `Unknown Source`
> - Check Launcher Settings again

Yes, now it works! Thank you!

**Comment by chr56** [comment]
Well, it is because Phonograph Plus is an `Unknown Source` application (Well, looks like that _only_ applications installed by Google Play can be `Known Source`). 
So, besides using third-party installers which faking the source to Google Play, there is no way to fix such problems. (~Or you can distribute your app to Google Play~, but Phonograph Plus has never such plan).

By the way, it seems that `Developer Mode` can be turned off once `Unknown Sources` are allowed (This doesn't turn off along with Developer Mode).

**Comment by chr56** [comment]
We have [Trouble Shooting & FAQ](https://github.com/chr56/Phonograph_Plus/blob/eaeba974a3a617068166eaf02c11abed85ff1963/docs/FAQ.md) now. 
Close!
