### ISSUE TITLE
[Feature Request] Whitelist

### ISSUE THREAD

**Issue by n00bundercover** [chr56/Phonograph_Plus#11]
It would be nice to be able to select one or multiple folders and then show only the music in those folders. Many users have all their music in one folder, it is easier to whitelist one folder than to blacklist all folders but one.

Thanks for your work!

**Comment by chr56** [comment]
Well, thank you very much, I would consider the whitelist in next versions.

**Comment by chr56** [comment]
Whitelist has been implemented in [0.4-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.4-dev1) now. 
Stable Release is coming soon in next few days.

**Comment by chr56** [comment]
[v0.4.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.4.0) was released. 
You can use `Path Filter` as Whitelist .

Closed!
