### ISSUE TITLE
[Bug]: Tapping on a song to play it makes the app think I want to select multiple songs

### ISSUE THREAD

**Issue by alphanerdgen** [chr56/Phonograph_Plus#110]
### Bug Summary

Tapping on a track makes a selection bar appear on top. See screenshots, please.

### Version

1.0.1

### Steps to reproduce the bug

1. Tap on a song.
2. Notice the new selection bar on top.
3. Now try going back to the main screen by tapping on the <- icon near the top left corner. You'll notice it's annoyingly persistent.

### Screenshots or Screen recordings

![Screenshot_Phonograph Plus1](https://github.com/chr56/Phonograph_Plus/assets/83120103/0c881cb2-5788-41eb-87a6-42ce7a5b77f1)

![Screenshot_Phonograph Plus2](https://github.com/chr56/Phonograph_Plus/assets/83120103/ddb5f592-7f32-4e62-bc46-34647d917e31)

### Environment

Android 12

### Other helpful information

Downloaded from F-Droid.

**Comment by chr56** [comment]
Fixed in [v1.0.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.2). Close!
