### ISSUE TITLE
[Feature Request] Enqueue song when selected

### ISSUE THREAD

**Issue by n00bundercover** [chr56/Phonograph_Plus#12]
This is how it works currently:

When you select a song, it is played and the other songs from the same album are enqueued automatically. When you select the next song, the queue is emptied, the song is played and the other songs from the same album are enqueued. You can long press a song (or album/artist) to add it to the queue without deleting the queue.

This is how I would like it to work.

When you select a song, if the queue is empty the song is played. If there are other songs in the queue already, the selected song is added to the queue.

Would really love to have this feature, maybe as toggable option. There is no open source music app out there that has it. I hope you can understand what I mean, I'm not a native speaker and my English is not perfect. But my Chinese is even worse... ;-)

Thanks for your work!

**Comment by chr56** [comment]
Yeah, the similar idea also occurs to me for a quite not short time. I once considered to let the user to define what would happen on clicking a song, but I am way too busy for other stuff.

I would take your suggestion into my development plan.

**Comment by chr56** [comment]
Yeah, the similar idea also occurs to me for a quite not short time. I once considered to let the user to define what would happen on clicking a song, but I am way too busy for other stuff.

I would take your suggestion into my development plan.

**Comment by chr56** [comment]
[Preview v0.5-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.5-dev1) is available now.

Go to `Custom behavior when clicking a song` in setting, check `If current queue is empty, play the queue directly`, and check `Append the song to playing queue`. This should be what you request.

**Comment by chr56** [comment]
[v0.5.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.0) is available released now.

**Comment by chr56** [comment]
It has been mouths. And I *think* the feature you request has been implemented already (November ladt year).


So, this issue *shall* be closed.
