### ISSUE TITLE
[Bug]: player notification is allways on screen 

### ISSUE THREAD

**Issue by bristentree** [chr56/Phonograph_Plus#121]
### Bug Summary

On my LG G8s with android 12, the notification of phonograph plus ist allways on even if I close the app. 
It is not possible to swipe it away.
To close it, I have to go in the app manager et force the closing.

Sorry for my English and thanks for this top app !

### Version

1.1.0

### Other helpful information

Package name:    player.phonograph.plus
App version:     1.1.0 (1010)
Git Commit Hash: 374a7e2791709a079348795f90898da90cba8a7e
Android version: 12 (SDK 31)
Device brand:    lge  (by LGE)
Device model:    LM-G810 (code: betalm)
Product name:    betalm_e
Build version:   SKQ1.211103.001 
                 (222720007a5f6.OPEN_EU_DS)
Hardware:        betalm
Language:        fr

**Comment by chr56** [comment]
This is "fixed" in Preview Release [1.2-dev6](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.2-dev6), and Stable Release may be released in next week.

**Comment by chr56** [comment]
[v1.2.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.2.0) released.

Now you can dismiss/cancel/swipe-away playback notification after 5 sec if paused.
