### ISSUE TITLE
[Feature Request] Shuffle play all tracks in a folder without manually selecting tracks one by one

### ISSUE THREAD

**Issue by dave-ml-xcv** [chr56/Phonograph_Plus#133]
### Desired behaviour:

1. Navigate to folder containing music files (either in Files or Folders tab)
2. Select Folder without opening inside it
3. Select "Shuffle all" from options menu
4. All tracks in folder are shuffled on queue, with first song being random as per shuffle

Alternatively, a "Shuffle play" button visible when browsing inside a folder, or at least the option to set that in Settings.

### Current behaviour:
1. Navigate to folder containing music files (either in Files or Folders tab)
2. Select Folder 
3. Select "Shuffle all" from options menu
4. Error displayed `Queue (size:0) submitted is empty or start position (0) is out ranged.`

To circumvent this I have to manually select all files in the folder and then select Shuffle All from options. It becomes very impractical for large folders with lots of music.

This can potentially be filed as a Bug as well because of the error above.

**Comment by dave-ml-xcv** [comment]
Some info about my device I forgot to add:

- Device type - Redmi Note 10 Pro
- MIUI Version 12.5.7
- Android ver 11

**Comment by chr56** [comment]
1. "Shuffle all" in drawer menu is for all songs. That is not working for your situation.
2. Buttons in "Folders" has been implemented in 372c72473:
Preview: [PhonographPlusPreview_372c72473.zip](https://github.com/chr56/Phonograph_Plus/files/14155786/PhonographPlusPreview_372c72473.zip)

**Comment by dave-ml-xcv** [comment]
Just tried the v1.4.5-dev1 APK. The issue seems to be resolved with this fix.

### Steps to confirm:

1. Navigate to Folders tab.
2. _Optional:_ Pull down to reveal top bar with buttons under tabs.
3. Click a folder, listing media files inside.
4. Press Shuffle from top bar under tabs. (_If step 2 not completed then pull down now to reveal buttons_)
5. All songs play shuffled as expected.

### Repeat of steps from original issue

Using the 'three dots' menu as before still did not work, however I am satisfied with this implementation for now, thanks.

### Recommendation

If I may recommend some better visibility for this option to shuffle (including in Files tab if it can be implemented the same way) this should prevent from duplicate issues on this topic. Potentially add to documentation if relevant?

**Comment by chr56** [comment]
After revision 2c02eedf, there are a new UI of `FILES` tab, which you can play or shuffle a folder.

This is _Preview_ channel build:
[PhonographPlus_Preview_Build_2c02eedf](https://github.com/chr56/Phonograph_Plus/files/15177379/PhonographPlus_PreviewBuild_2c02eedf.zip)

**Comment by chr56** [comment]
All unfinished works are done since [v1.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.0). Close!
