### ISSUE TITLE
[Bug]: Colour refresh after pressing the shuffle button

### ISSUE THREAD

**Issue by JonnyVR1** [chr56/Phonograph_Plus#134]
### Bug Summary

Colour refresh when shuttle button is pressed, often new colour bears no resemblance to any of the colours in the album art. For instance I have a completely blue album art and after pressing shuffle the player colour switches to yellow.

### Version

1.4

**Comment by chr56** [comment]
This bug has been fixed in 1a3c5929. 

Preview version [v1.5-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.5-dev2) contains the fix above.

**Comment by chr56** [comment]
Phonograph Plus [v1.5.0](https://github.com/chr56/Phonograph_Plus/releases/tag/c) has been released. Close!
