### ISSUE TITLE
[Bug]: skip/rewind button says "couldnt play this song (deleted)" when que is looping

### ISSUE THREAD

**Issue by 1sad** [chr56/Phonograph_Plus#135]
### Bug Summary

when you press skip/rewind, and the playlist loops, it brings up the message. still plays but there is a message.

### Version

1.4.0

### Steps to reproduce the bug

add song to que
play song
press skip/rewind

### Screenshots or Screen recordings

![Screenshot_2023-11-19-13-20-13-753_player phonograph plus](https://github.com/chr56/Phonograph_Plus/assets/23120024/66b08154-ca67-4c60-bbd6-7120539c7ebf)

### Other helpful information

another relevant thing is that it may have a hidden benefit of letting scrobble apps scrobble 1 track loops properly. usually when 1 song is playing, it only gets scrobbled one time, and to scrobble it multiple times you have to pause and play, or add something else.

**Comment by chr56** [comment]
Fixed in [v1.4.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.2). Close!
