### ISSUE TITLE
[Bug] Albums under interpret are not sorted by release date

### ISSUE THREAD

**Issue by eku** [chr56/Phonograph_Plus#146]
### Bug Summary

If the collection contains several albums for an interpreter, it is expected that they are ordered according to the release date (cover flow). This is how the original phonograph app works. I also cannot find sorting option like elsewhere.

### Version

1.4.3

### Environment

LineageOS 20 (AOSP 13).

**Comment by chr56** [comment]
Well, that is, albums of an _interpreter_/artist is sorted by _global setting_ (sorting option in Albums tab).

**Comment by chr56** [comment]
Fixed in c140a622.

**Comment by eku** [comment]
> Well, that is, albums of an artist is sorted by _global setting_ (sorting option in Albums tab).

You are right. But you wouldn't want it that way at this list.

**Comment by chr56** [comment]
[v1.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.0) released. Close!

Reopen or open a new Issue if you have more questions.

**Comment by eku** [comment]
PhonographPlus_1.7.1-beta1 has again the isssu

**Comment by chr56** [comment]
> PhonographPlus_1.7.1-beta1 has again the issue

Fixed in 5863d9e9
