### ISSUE TITLE
[Bug] Playing que doesn't repeat after skipping final song while connected via Bluetooth

### ISSUE THREAD

**Issue by glowmoss** [chr56/Phonograph_Plus#148]
### Bug Summary

As the title says. I try to skip the final song while in my car to get back to the first and instead of repeating it it just ends the song. In the original phonograph it works as intended. If I skip it on my phone it works but I can do that while driving lol.

Also another issue I had was sometimes when connecting to my car it wouldn't start the song and I had no control unless I unlocked my phone and pressed play. The app has unrestricted battery use and again the original doesn't have the issue.

### Version

1.4.3

### Steps to reproduce the bug

While connected to the car use the car to try and skip the final song and it will just end the song 

### Environment

Graphene OS Android 14

**Comment by chr56** [comment]
So,
1. Playback controls in car is as **same** with playback notification.
   So, the first bug (incorrect queue repeat) happened in playback notification as well. It was confirmed.
2. No control without starting application is _considered as normal_.
   As it described in 1: Car Playback Controls is Playback Notification. So, Playback Notification on the phone is dismissed or not showed up (like, just after starting application util you play something),  also means Car Playback Controls not showing. So you have to unlock phone and click something.
   I do not think this is a bug, yet it's a _behaviour_. (It is not wise to show a paused Playback Notification just after starting application) Actually, I do not even want to "fix" it, but maybe make it a user opt-in preference in future.
3. Android Auto, are you use it?

**Comment by glowmoss** [comment]
No I don't use Android auto. My car just has Bluetooth playback. 

That's strange as I have never had that issue with the original phonograph app unless the battery settings were set to anything but unrestricted. I have gone back to using it for now as I have never had to unlock my phone and screw around with it. I just connect with Bluetooth and it continues with no issue. I really do like the improvements on this version though and will keep an eye on it

**Comment by chr56** [comment]
[v1.4.4-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.4.4-dev1) has been released!

This should contain fix for first bug you describe.

**Comment by glowmoss** [comment]
Thanks I will check out how it goes tomorrow

**Comment by glowmoss** [comment]
That seems to be working now. I forgot to come back and comment on it.

**Comment by chr56** [comment]
Stable Release [v1.4.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.4) has been released!

The main problem has been solved, I think.

Now, there are only two problems remaining:
1. An option of "dismissible and persistent Playback Notification";
2. Issue of Battery Optimisation. Once the first one is implemented, I think application would not be killed easily. (See also #97)

These may be implemented in version _1.5.*_, and if you do not mind, this issue would be closed anyway.

**Comment by glowmoss** [comment]
I just found something else that's possibly quick for you to fix. I hope you don't mind me just putting it here. 
When you have it set to repeat a single song. if you try to go to another song through a Bluetooth device or through the notification it will just repeat the song. If you go into the app and press the forward or back button it will change as expected though.

**Comment by chr56** [comment]
1. Persistent Playback Notification has been implemented in v1.5-dev1.
Preview version [v1.5-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.5-dev1) has released.
Now you could toggle on `Persistent Playback Notification` in Settings.

2. "Skip" in Notification/Connected Devices plays same performance as natural playing behaviour.
For example, in "Single Song Repeat" mode:
If you "skip" in UI, it goes the next one;
If you "skip" in Notification/Connected Devices, it will jump to beginning and just repeat it again, just as **Song is already ended naturally** and it need repeat following your settings.
Actually, I do **NOT** want to change this behaviour.

**Comment by glowmoss** [comment]
Alright if I want to repeat a lot I will just keep using the original phonograph. I seem to hardly use this app beyond editing some tags that the original can't lately. I have a speaker that only has a skip forward and play function and volume control so I can't even skip back on that to replay a song so it's easier to skip when I am done listening to a song  outside of repeat single song option. I feel like this is the first app I have used that works that way as when you are in the app the buttons skip forward and back as expected then the notification acts differently just infinitely repeating which when you can't access the device is annoying to say the least.
