### ISSUE TITLE
[Bug] It is not possible to change the playback speed by setting it via text.

### ISSUE THREAD

**Issue by chenhuicui** [chr56/Phonograph_Plus#149]
### Bug Summary

During the song playback process, it is not possible to change the playback speed by setting it to 1.50 through text.

### Version

1.4.1

**Comment by chr56** [comment]
Please press `Enter`/`OK` to confirm your input.

**Comment by chenhuicui** [comment]
https://github.com/chr56/Phonograph_Plus/assets/91791080/cd0cae0e-3de1-4fba-befd-5de5ebd2848e

it seems not work.

**Comment by chr56** [comment]
Use `Enter` in **IME**.

**Comment by chr56** [comment]
Click `Enter` in your IME **before** press `Set`:


https://github.com/chr56/Phonograph_Plus/assets/30681738/5f91777f-fcc1-4d31-9fed-f5b527fd3636
