### ISSUE TITLE
[Bug] Difficulty uninstalling the application

### ISSUE THREAD

**Issue by Dim7x0** [chr56/Phonograph_Plus#151]
### Bug Summary

I can’t uninstall an application from Android 10. The package installer crashes with an error when I try to uninstall the application.

### Version

1.4.4.

**Comment by chr56** [comment]
Report to device manufacturer.

This shall not be fault of Phonograph Plus.


Try to use adb to uninstall if in urge.

**Comment by chr56** [comment]
This maybe a bug on **Android 10** with **external physical SD card**.

Phonograph Plus has set `android:hasFragileUserData="true"` in [AndroidManifest.xml](https://github.com/chr56/Phonograph_Plus/blob/v1.4.4/app/src/main/AndroidManifest.xml#L28) years ago (cf8036d204edd1947a7881942654a8309132bf2c).

However, there is bug:
https://gist.github.com/agnostic-apollo/58def38fdb1c90563454974108ae52df
If you are using Android 10 with an external physical SD card. Package Installer will directly crash.

However, Google fixed it on Android 11.

This is a fault by Phonograph Plus. And this was also reported last year (#86) but I didn't notice and see the truth.


See also:
Similar issues: 
MuntashirAkon/AppManager#1193
hushenghao/AndroidEasterEggs#24

**Comment by chr56** [comment]
Current solutions:

1. Guide user to use `adb` to uninstall:
   `adb uninstall player.phonograph.plus`
2. Remove `android:hasFragileUserData` in `AndroidManifest.xml`:
   Is that worthy?
3. Provide special version to Android 10 users: (**currently plan**):
   A version without `android:hasFragileUserData="true"` (and `targetSdk` is 28 to bypass _Scoped Storage_), this will solve the problem (and many issues relative to storage permissions).

**Comment by chr56** [comment]
If everything is fine, in next major version, there would be a special version provided for Android 10 with external SD card. 
You could upgrade to this special version which could be uninstall without difficulties.

**Comment by chr56** [comment]
[v1.8.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.0) has been released.

Please install `legacy` variant for Android 10, which would fix the problem.

Close! @Dim7x0
