### ISSUE TITLE
[Feature Request] Ignore Audio focus (Always Play Media in Background)

### ISSUE THREAD

**Issue by deception-andpitfalls** [chr56/Phonograph_Plus#154]
There don't seem to be existing issues, so I will jump ship. 
Request for the implementation of an "Always Play Media in Background" feature, regardless of any ongoing activity, similar to the following apps:

1. RetroMusicPlayer
https://github.com/RetroMusicPlayer/RetroMusicPlayer
![Screenshot_20240220-091705.png](https://github.com/chr56/Phonograph_Plus/assets/105056343/7df78c9d-3ab4-488b-b507-2d0bf3d59bcd)

2. APlayer
https://github.com/rRemix/APlayer
I injected a script to disable screenshots in the APlayer app since it's my primary audio player. 
I apologize for not providing a picture of the features, as it will cost me time and data plan.

I listen to instrumental and vocal music while engaging in other activities. It helps stimulate my brain chemicals, especially considering my nutritional deficiencies and serves as a coping mechanism for anxiety and sensory deprivation in my environment.

**Comment by chr56** [comment]
Initial implementation has been done in 3739dcc4:

[IgnoreAudioFocus_3739dcc4.zip](https://github.com/chr56/Phonograph_Plus/files/14522887/IgnoreAudioFocus.zip)

I am not sure is there any conflictions insides (especially with preference _ResumeAfterAudioFocusGain_) or outsides, and it tests fine on my cases.

**Comment by chr56** [comment]
This may be have confliction with audio output of Android Auto. This maybe result in no sounds in Android Auto.

**Comment by chr56** [comment]
[v1.6.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.6.0) has released, close!
