### ISSUE TITLE
[Crash Report] Crash when play a music after force stop

### ISSUE THREAD

**Issue by BinTianqi** [chr56/Phonograph_Plus#159]
### Crash log

```
Crash Report:

Package name:    player.phonograph.plus
App version:     1.5.1 (1051)
Git Commit Hash: 980d8b5c5054cadf889c954ef9aff1c21efcdce6
Android version: 14 (SDK 34)
Device brand:    OnePlus  (by OnePlus)
Device model:    GM1901 (code: OnePlus7)
Product name:    OnePlus7
Build version:   lineage_guacamoleb-userdebug 14 UQ1A.240205.004 f8f14577f3 
                 (f8f14577f3)
Hardware:        qcom
Language:        zh


Stack Track:
androidx.datastore.preferences.protobuf.l1: lateinit property fetcher has not been initialized
	at androidx.activity.d.run(SourceFile:33)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)


```

### Version

1.5.1

### Steps to reproduce the bug

1. Force stop the app or reboot system
2. Restart the app
3. Play a music
4. Crash
5. (Reopen the app)
6. (Play the music played in step 3, the app crash again with same log) (or play a different music, it will be fine)

### Environment

see crash log

**Comment by chr56** [comment]
I am confused. I force-stop it frequently as you do, but I have never met this.

And are you sure that "_play a different music, it will be fine_"?

**Comment by chr56** [comment]
Try this one

[Test.zip](https://github.com/chr56/Phonograph_Plus/files/14473086/Test.zip)

**Comment by BinTianqi** [comment]
> Try this one
>  [Test.zip](https://github.com/chr56/Phonograph_Plus/files/14473086/Test.zip)
> 

I changed the package name of this apk to the release package name, and then used CorePatch to overwrite the installation of the original app. This issue no longer occurs. Finally I reinstalled the original app, and this problem reappeared.

I think this problem has been solved.

**Comment by BinTianqi** [comment]
> Try to turn off `Broadcast synchronized lyrics` (`实时发送歌词`).

I turned it off when I tried to reproduce this issue

**Comment by chr56** [comment]
> I think there is no relation between this issue and `Broadcast synchronized lyrics`

The stacktrace indicated that it crashed when broadcasting lyrics.

**Comment by chr56** [comment]
> I changed the package name of this apk to the release package name, and then used CorePatch to overwrite the installation of the original app. This issue no longer occurs. Finally I reinstalled the original app, and this problem reappeared.
> 
> I think this problem has been solved.

Package name with suffix `.preview` is Preview Channel build (used in Github Release with "preview release" and test  for solving issue).

The next release in Stable Channel is about in middle or end of this month.
