### ISSUE TITLE
[Bug] A couple of minor issues 

### ISSUE THREAD

**Issue by George123451** [chr56/Phonograph_Plus#161]
### Bug Summary

Hi chr56, 
I found a couple of minor issues I wanted to report so I made this account. 

1. Just a small annoyance for me but I think you have Word wrap on the play lists tab as the s appears under playlist. 

2. The coloured navigation bar setting doesn't actually do anything for me. For me its always coloured. I use gesture navigation just so you know, if that might be affecting it idk. Sometimes it's not even any of the colours I set for the bar at the top and bottom. In the pic I will attach the colours set are purple and that light pink with coloured navigation bar off.

3. The repeat single song option is pretty annoying if you connect to a Bluetooth device and want to skip forward using said Bluetooth device. Sometimes I just leave it on one song, then use the speaker to skip to another but on this app I have to use my phone to go to the next song instead. Idk if that's intentional or not but is annoying none the less. 

Thanks for your time chr56 you are doing great on this app so far

### Version

1.5.2

### Environment

Android 14

### Screenshots or Screen recordings

![Screenshot_20240309-234901](https://github.com/chr56/Phonograph_Plus/assets/162804906/5d472b98-f402-458d-952b-2f5ef296c4dd)

**Comment by chr56** [comment]
Well,

1. I am afraid that is device specific especially screen size or dpi:
![Screenshot_20240309-213723_Phonograph_Plus_Preview](https://github.com/chr56/Phonograph_Plus/assets/30681738/bd59e1fa-aac1-4a8c-ae43-8eeec68f2448)
2. Confirmed. 
But actually it is not coloured util you slide player up and down; it would not recover.
3. So are you "another one" who wants _Bluetooth/Notification_ control acts as _Graphic_ User Interface control, just like the issue #148?

**Comment by George123451** [comment]
1.That's annoying I was hoping that was just some word wrap setting or something. If nothing can be done I will just live with it. 

3. I didn't see that it would be a nice feature but if it's too hard or you prefer it like that I will just make a playlist with the same songs on it so many times as a way around it when using the speaker as I don't want to be too much of a hassle for you. You do do this for free so you do what you want to do honestly.

**Comment by chr56** [comment]
1. tabs: I am considering System Fonts for your situation.
2. now here is a Preview version which: 1) slightly adjust width of tabs; 2) Bluetooth/Notification control now acts as asme as Graphic User Interface control

[PreviewRelease_d6f721af.zip](https://github.com/chr56/Phonograph_Plus/files/14582432/PreviewRelease_d6f721af.zip)

**Comment by George123451** [comment]
In that build the playlists tab is normal now and thanks for adding the ability to skip like the normal gui control. 

I think the only issue left is the coloured bars when pulling the playing que up.

**Comment by chr56** [comment]
Navigation Color should be fixed in this revision:

[PreviewRelease_aa720c59.zip](https://github.com/chr56/Phonograph_Plus/files/14590310/PreviewRelease_aa720c59.zip)

**Comment by George123451** [comment]
Thanks everything is working as expected. I will close this now
