### ISSUE TITLE
[Feature Request] the option to remove/hide images or icons

### ISSUE THREAD

**Issue by Nihil901** [chr56/Phonograph_Plus#162]
Hi, so i wonder if you can add the option to remove images  something like that: 
![Screenshot_2024-03-18-01-08-18-03](https://github.com/chr56/Phonograph_Plus/assets/141766629/7ffbd94c-9a1e-4891-9a01-a570c9c549d7)

**Comment by chr56** [comment]
New Item Layouts:
- `List (2 lines, no image)`
- `List (3 lines, no image)`

have been implemeted in 650157d9 d159f034 9145048c.

Preview build for test: 

[preview_no_image.zip](https://github.com/chr56/Phonograph_Plus/files/14665980/preview_no_image.zip)

**Comment by chr56** [comment]
[v1.6.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.6.0) has released, close!

**Comment by Nihil901** [comment]
Wow thank you so much, i'm too late sorry for not relying long ago
