### ISSUE TITLE
[Bug] Minor UI flaws (Text, Color)

### ISSUE THREAD

**Issue by shezik** [chr56/Phonograph_Plus#163]
### Bug Summary

The confirmation dialog of adding path to the path filter always says it's in 'blacklist' mode independent of whether it is actually in exclude or include mode.

### Version

1.6-dev2

### Environment

Package name:    player.phonograph.plus.preview
App version:     1.6-dev2 (1054)
Git Commit Hash: 0461b57eee4fe46b1606f397ed910c3d80cde14b
Android version: 11 (SDK 30)
Device brand:    blackshark  (by blackshark)
Device model:    SHARK PRS-A0 (code: penrose)
Product name:    PRS-A0
Build version:   PROS2203050CN00MR2 
                 (V12.0.1.0.RBICNBS)
Hardware:        qcom
Language:        zh

### Screenshots or Screen recordings

![Screenshot_2024-03-25-11-44-01-545_player phonograph plus preview](https://github.com/chr56/Phonograph_Plus/assets/47771243/c53dad6c-6b41-44ef-af28-5dd6c0200aa0)
![Screenshot_2024-03-25-11-44-06-143_player phonograph plus preview](https://github.com/chr56/Phonograph_Plus/assets/47771243/46b07acb-8928-4ab8-a601-70c8fdc06d62)

**Comment by chr56** [comment]
Confirm.

That is just a minor UI glitch.

**Comment by shezik** [comment]
Btw the buttons under the "Last added playlist interval" dialog in settings seem to use the Primary Color while other similar dialogs use the Accent Color instead. Not a big deal, not even that noticeable but once you see the inconsistency it bugs me a bit. Thank you for your great work!

**Comment by chr56** [comment]
Dialog button color flaw is confirmed.

**Comment by chr56** [comment]
Text issue was fixed in 89d5eb6f;
Color issue was fixed in 93a4fd11;

Preview Build: 
[PhonographPlus-PreviewRelease-93a4fd11.zip](https://github.com/chr56/Phonograph_Plus/files/14897248/PhonographPlus-PreviewRelease-93a4fd11.zip)

**Comment by shezik** [comment]
It works! Thanks a lot! :D
