### ISSUE TITLE
[Bug] Duplicated Items in Playing Queue

### ISSUE THREAD

**Issue by TTTUUUIII** [chr56/Phonograph_Plus#168]
### Bug Summary

A song in the playlist will be repeated multiple times in a row(did not do anything)，this causes it to be played many times in succession. I don't know if this is a problem, but it's not a great experience.
<img src="https://github.com/chr56/Phonograph_Plus/assets/107593190/bac45790-37f5-4a52-a0dc-7e486650a478"  height=800 />

### Version

1.6-dev2

**Comment by chr56** [comment]
Excuse me, _I do not know what you are talking about_! Please describe it from very beginning.

What playlist? Or **where is this playlist generated from** (Phonograph Plus or other applications)?
If it is produced by Phonograph Plus, please also tell me the **steps to reproduce**.
And can you **view** this playlist in raw file format, to see if there are multiple same items as you said?

**Comment by TTTUUUIII** [comment]
Sorry, I didn't express this question accurately for you. 

For example:
I open the app and start playing music，like this:
<img src="https://github.com/chr56/Phonograph_Plus/assets/107593190/162015f7-d09b-4b78-985d-370c4b6beb28" height=500 />

**I often find that after *"Soul to Soul"* (just an example) is played, the next song will still play *"Soul to Soul"* again**. When I came to the play page, there was a list titled *"Up next"* at the bottom. I found that *"Soul to Soul"* would appear multiple times in this list. As you can see in the screenshot above, *"Hotel California"* is repeated twice and *"17"* is repeated five times.

Device: Pixel 7 Pro
System Language: zh-CN

**Comment by chr56** [comment]
How do you start playing this "PlayingQueue"? How do these songs enter your PlayingQueue? And can you see some pattern of this behavior?

Sorry, I can still not gain enough information to locate and fix this bug, as well as I could reproduce the strange behavior as you described on my side. Sorry.

**Comment by TTTUUUIII** [comment]
Hi，I know how to reproduce this problem，Click a song 5 times in a row under the "SONGS" tab, and This song will be played in a loop 5 times. By the way，all songs are located in the Music directory.

step 1:
<img src="https://github.com/chr56/Phonograph_Plus/assets/107593190/a619b767-5fde-40e8-9f67-5fb6c452fd02" height=500 />

step 2:
<img src="https://github.com/chr56/Phonograph_Plus/assets/107593190/b5726cbe-d3d6-4439-860a-4b24b9caef70" height=500 />

Is this normal?

**Comment by chr56** [comment]
Ehh... Well, that is not a bug; this a feature by design.

Please go to `Setting` -> `Content`(`内容`) -> `Custom behavior when clicking a song`(`单击歌曲时行为`)， to **change this behavior**.

**Comment by TTTUUUIII** [comment]
Based on your tips, I reset this option to my liking and it's much better now, thank you. :grinning:
