### ISSUE TITLE
[Feature Request] Remember last folder

### ISSUE THREAD

**Issue by EkkiBrue** [chr56/Phonograph_Plus#170]
I really love Phonopraph. Thank you all for your time, effort and passion you put in it. 

I use a folder based approach using my local MP3 collection on my SD Card. When playing files and browsing through the directories I press the "back" button to get back to the last directory. But it alway gets me back to the root of the folder and does not reckognize the last position in my filelist where I left last. 

Is it possible to implement this ? Or is it already there and I didn´t recognize the feature ?

THX in advance,
all the best,

**Comment by chr56** [comment]
Well, I would consider this feature.

By the way, you can change the Start Directory (`Set as start directory` in the menu of a directory) as a workaround, though that is not very perfect and suitable.

**Comment by EkkiBrue** [comment]
> By the way, you can change the Start Directory

Yepp. Doing this already. But its really complicated if you have your Artists Folder following the Album-Name folders.
Going back gets me back to the Artists Folder but if I again push back the lists starts with the root file - It should scroll back automatically to the folder which I used last. Now it shows the root again starting from the beginning with "A" (when sorting by name).

Thanks again for you consideration...

**Comment by chr56** [comment]
I am kind of busy now (at least till mid-May), such problems (maybe along with #77) may be solved or improved in next major version.

**Comment by EkkiBrue** [comment]
Nice! Thanks for considering...

**Comment by chr56** [comment]
After b05ae997, `FILES` tab (not `FOLDERS` tab) can remember **last position** till next reboot.


This is _Preview_ channel build:
[PhonographPlus_Preview_Build_b05ae997](https://github.com/chr56/Phonograph_Plus/files/15145223/PhonographPlus_Preview_b05ae997.zip)

This is just temporally workaround. The complete functional feature may be implemented in about June (approximately 1.8.x or 1.9.x), please be patient.

**Comment by chr56** [comment]
After revision 2a9176bd, `FOLDERS` tab can remember last scroll position till next reboot.
After revision 2c02eedf, there are a new UI of `FILES` tab like other tabs.

This is _Preview_ channel build:
[PhonographPlus_Preview_Build_2c02eedf](https://github.com/chr56/Phonograph_Plus/files/15177379/PhonographPlus_PreviewBuild_2c02eedf.zip)

**Comment by EkkiBrue** [comment]
Wow... Thank you very much! Hope to see the release soon on Fdroid ;)  This player is my #no1 choice for audio players on Android.,,

**Comment by chr56** [comment]
This feature should be included in
 v1.6.3, which may be released in mid-May if everything is fine. (F
-droid reproducible build may be lagging
 for about 3 or 4 days).

This issue would be closed once new version released.

**Comment by chr56** [comment]
[v1.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.0) released. Close!


PS: you could not be waiting for on F-droid.

> Reproducible Builds are enabled on F-droid, Apks from F-droid shall be exactly equivalent to ones from GitHub Releases, byte by byte.

> Reproducible Build has enabled, meaning the F-droid apk signature should be replaced as same as the GitHub one.
