### ISSUE TITLE
[Bug] 'Remove from playlist' action is missing

### ISSUE THREAD

**Issue by pixel2user** [chr56/Phonograph_Plus#171]
### Bug Summary

In playlist view the action menu for a track is still missing a 'Remove from playlist' action. Instead the 'Remove from playing queue' action is shown - which is only working in 'playing queue' view.

### Version

1.6.0

### Steps to reproduce the bug

1. Open a playlist
2. Open the action list for a track

### Screenshots or Screen recordings

![Screenshot_20240417-171215](https://github.com/chr56/Phonograph_Plus/assets/25106680/1293f27b-da71-490c-8dc2-77fea4e41231)

**Comment by chr56** [comment]
![Screenshot_2024-04-17-23-28-00-55_ab102787fb2ce6a5e4dc783e900cc285](https://github.com/chr56/Phonograph_Plus/assets/30681738/08176606-baf0-490d-8b2c-068d2297eff1)

Please enter `Editor` mode: `Playlist Menu` -> `Edit...`

**Comment by pixel2user** [comment]
Thanks for the clarification! But I'm still not sure why a 'Remove from playing queue' action is needed in the playlist view.

Does the action work for you? For me it doesn't remove the track from the queue.

**Comment by chr56** [comment]
Sorry, `Remove from playing queue` is certainly a bug.

**Comment by chr56** [comment]
[PhonographPlus-Preview-6a31b287.zip](https://github.com/chr56/Phonograph_Plus/files/15013424/PhonographPlus-Preview-6a31b287.zip)

`Remove from playing queue` has removed since 6a31b287
