### ISSUE TITLE
[Bug] blank in app widget at start

### ISSUE THREAD

**Issue by Dim7x0** [chr56/Phonograph_Plus#172]
### Bug Summary

There are no player buttons on the widget after restarting the smartphone. you have to poke your finger at random to make them appear.
android 10

### Version

1.4.4.

### Screenshots or Screen recordings

![Image](https://i.postimg.cc/FsdpQwdY/Whats-App-Image-2024-04-22-at-09-19-10.jpg)

**Comment by chr56** [comment]
That is because Phonograph Plus is **not running**. 
And it seems that launching in background after booting system is forbidden since Android Oreo (8).

**Comment by Dim7x0** [comment]
> That is because Phonograph Plus is **not running**. And it seems that launching in background after booting system is forbidden since Android Oreo (8).

maybe. but the widgets of other (soundcloud, youtube, mx player,...) after booting system players do not have such problems. Okay, anyway, the app is working fine.
[https://i.postimg.cc/zvH3z2zf/Screenshot-20240426-190234.png](url)

**Comment by chr56** [comment]
I think there is no more problem in [v1.6.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.6.2).

Close!

_Reopen (Or create a new issue) if you have more problem._
