### ISSUE TITLE
[Feature Request] Change song order in playing queue

### ISSUE THREAD

**Issue by pinckpockett** [chr56/Phonograph_Plus#174]
When songs are added to the queue. The order cannot be changed. Having the ability to move the songs around in a queue would be a great addition. An exmple would br like in the metro music app found in f-droid.

**Comment by chr56** [comment]
What? Can not you reorder songs in playing queue by long pressing  index numbers and draging and dropping?

**Comment by chr56** [comment]
Close! 
Reopen it if you have more questions. Or open another issues if you have other problems or questions.

**Comment by pinckpockett** [comment]
> Close! Reopen it if you have more questions. Or open another issue if you have other problems or questions.

Thank you very much. I had no idea this could be done. Apologies for making an issue for this. It seems like I cannot be delete posts once they are made but I appreciate you showing me how to reorder the queue. 

Could you please delete my issue so it won't clutter up your project?

**Comment by chr56** [comment]
Are you sure?

Do you really want to **DELETE** this issue.
