### ISSUE TITLE
Wrong string in Export Dialog

### ISSUE THREAD

**Issue by uli-on** [chr56/Phonograph_Plus#177]
The Export screen displays the wrong string, namely Import Backup instead of Export Backup. Not a translation typo, cause it's like that in both German and English languages. 

Edit: Phonograph plus v 1.6.2

**Comment by chr56** [comment]
Yes, Export Backup Dialog uses wrong string: [BackupExportDialog.kt#L52](https://github.com/chr56/Phonograph_Plus/blob/v1.6.2/app/src/main/java/player/phonograph/ui/dialogs/BackupExportDialog.kt#L52)

**Comment by chr56** [comment]
Fixed in `28fca42e`

**Comment by chr56** [comment]
[v1.6.3](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.6.3) has been released. Close!
