### ISSUE TITLE
[Bug] No cover display going back from single album to albums per artist

### ISSUE THREAD

**Issue by eku** [chr56/Phonograph_Plus#179]
### Bug Summary

Going for and back in artist's albums makes covers black, i.e. not displayed.

### Version

1.6.2

### Steps to reproduce the bug

1. Choose an artist with multiple albums 
2. Tap on one album to see song list (right one)
3. Tap back to return to artist

### Environment

AOSP13

### Screenshots or Screen recordings

![Bildschirmfoto vom 2024-05-08 17-29-34](https://github.com/chr56/Phonograph_Plus/assets/418685/88637c69-ba59-456e-b7e5-5d0a919ea54a)
![Bildschirmfoto vom 2024-05-08 17-29-58](https://github.com/chr56/Phonograph_Plus/assets/418685/a4d74192-ca60-48d0-b6a0-f8ee071d4fcb)
![Bildschirmfoto vom 2024-05-08 17-30-23](https://github.com/chr56/Phonograph_Plus/assets/418685/1a83dc01-556e-4e1c-b5dd-e27b0a4d0e06)

### Other helpful information

This happens to any artist/album.

**Comment by chr56** [comment]
Confirmed.

**Comment by chr56** [comment]
Fixed in [v1.7.1-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.7.1-dev2).

**Comment by eku** [comment]
Looks like the fix causes #188.

**Comment by chr56** [comment]
> Looks like the fix causes #188.

No, this exists before the fix.

**Comment by chr56** [comment]
[v1.7.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.1) has released, closed!
