### ISSUE TITLE
[Bug] No Song when using legacy way to read file

### ISSUE THREAD

**Issue by AdityaMishra135** [chr56/Phonograph_Plus#182]
### Bug Summary

![Screenshot_2024-05-09-08-34-42-441_player phonograph plus preview](https://github.com/chr56/Phonograph_Plus/assets/94228705/a4a2b9ff-ac17-4586-a4da-77351f24f92e)
![Screenshot_2024-05-09-08-34-35-250_player phonograph plus preview](https://github.com/chr56/Phonograph_Plus/assets/94228705/9236184f-c1f8-4ab2-b144-eaf551d387bc)

Normally when not tick legacy way to read file then its showing song in folder. But when using legacy way to read file then its showing no Song in folder.

### Version

Latest dev-2

**Comment by chr56** [comment]
Legacy way do not scan subfolders. The count actually should not be shown.

**Comment by chr56** [comment]
Song count has been hidden since revision 5a68d101.

**Comment by chr56** [comment]
[v1.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.0) released. Close!
