### ISSUE TITLE
[Bug] album sorting does not work

### ISSUE THREAD

**Issue by xraynaud** [chr56/Phonograph_Plus#189]
### Bug Summary

Since version 1.7.0, the sorting of albimums does not work. If i change the sorting (e.g from album to artist or year), nothing happens. 
Attached is a screen capture of the album view with albums sorted by number of songs. 

### Version

1.7.0

### Steps to reproduce the bug

Open phonograph plus, switch to album view

### Environment

Androi 14 on samsung a13

### Screenshots or Screen recordings

![Screenshot_20240608_163153_Phonograph Plus](https://github.com/chr56/Phonograph_Plus/assets/7243861/5a149be4-65e9-45c4-9256-4152f64e1f04)

**Comment by chr56** [comment]
[v1.7.1-beta1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.7.1-beta1) just fixed this problem hours ago.

**Comment by chr56** [comment]
[v1.7.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.1) has released, closed!
