### ISSUE TITLE
[Bug] Songs don't start playing when opening them from the file manager

### ISSUE THREAD

**Issue by ICloneableX** [chr56/Phonograph_Plus#196]
### Bug Summary

Upon clicking a song file in the file manager app (I tested on two different ones), I'm prompted to select one of the following options:

a. Play the song next
b. Play the song right now (at top)
c. Append the song to playing queue
d. Repeat this song only

If I understand correctly, both options b and d should start playing the song immediately. But they don't.

Current behavior:
- Option b adds the clicked song to the top of the queue but keeps playing the current song (if any) even though the UI is showing the clicked song as the one currently playing. And if nothing was playing, it just adds the clicked song to the top of the queue, then if you click the play button, it plays/resumes the last song, not the clicked one.
- Option d clears the queue and adds the clicked song, then just like option b, it either keeps playing the current song (if any) or does nothing.

Expected behavior:
- The song should start playing immediately if option b or d is selected.
- It would be nice to have a setting for the default action when a song is opened from the file manager (similar to the one for clicking a song in the player) and have 'Show prompt' as one of the options.

### Version

1.7.1

### Environment

Tested on Android 11 and Android 14

**Comment by ICloneableX** [comment]
Sorry to bother you again. Are there any plans to address this bug? This makes the app unusable for me.
Please let me know if you need more information about the bug. Thank you!

**Comment by chr56** [comment]
I am kind of busy now. Maybe at end of this mouth?

**Comment by chr56** [comment]
There is a temporal fix in _Preview Channel_ [v1.8.0-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.8.0-dev2).

**Comment by chr56** [comment]
[v1.8.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.0) has been released.

**Comment by chr56** [comment]
Preview version [v1.8.1-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.8.1-dev1):

- [x] Improved dialog.
- [x] Correct behaviors of playing instantly after some of choices.
- [ ] Default behaviors settings.

**Comment by chr56** [comment]
Preview [v1.8.2-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.8.2-dev1) has been released.

"Default behaviors settings" has been implemented.

There maybe some bugs.

This issue would be closed once stable is available.

**Comment by chr56** [comment]
[v1.8.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.2) has been released!

Close!
