### ISSUE TITLE
[Problem] Exporting application settings does not save user interface color settings. 

### ISSUE THREAD

**Issue by Dim7x0** [chr56/Phonograph_Plus#204]
Hi! Can you add this option)?

**Comment by chr56** [comment]
Which version?

> **1.7.0 2024.05.20**
> ...
> 3.New: Theme and Theme Colors can be corrected exported in backups file
> ...

This is already solved since v1.7.0.
So, ~How long have not you updated Phonograph Plus?~

**Comment by Dim7x0** [comment]
Sorry, I used an old backup file in the new version of the application)...

**Comment by chr56** [comment]
That is allright, it looks that there is no more problem.

Close!
