### ISSUE TITLE
[Feature Request] "Check upgrade" -> "Check for updates"

### ISSUE THREAD

**Issue by SpitFire-666** [chr56/Phonograph_Plus#206]
Minor nitpick about the wording! It could be "Check for update" or "Check update" etc 

![image](https://github.com/user-attachments/assets/0810b6fa-3199-4312-b3e4-77378509e99a)

**Comment by chr56** [comment]
Done in [v1.8.1-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.8.1-dev2).

Close
