### ISSUE TITLE
[Bug] Clicking on albums requires multiple tries?

### ISSUE THREAD

**Issue by shibedrill** [chr56/Phonograph_Plus#210]
### Bug Summary

Affects these versions: 1.8.1, 1.8.2. Running on LineageOS 21.

When scrolling through the Albums tab, if I attempt to click on an album to view its tracks, it doesn't bring up the album view around 50% of the time. The search icon will briefly flicker, and I get the tap animation/sound, but nothing else happens. The only way I can get the album to open is by clicking on the tile multiple times.

Expected behavior: clicking on an album once will open the album view.

Actual behavior: clicking on an album requires 1-5 attempts before the album view opens.

### Version

1.8.1, 1.8.2

### Steps to reproduce the bug

1. Open the app and navigate to the albums tab
2. Click on an album
3. If it opens right away, exit the album view and click on another album 
4. Repeat steps 2-3 until clicking on an album does not open the album view
5. Click on the same album 2-5 more times, and it will open the album view 

### Environment

LineageOS 21 Nightly, rooted via Magisk.

### Screenshots or Screen recordings

<details>
<summary>Screen recordings</summary>

https://github.com/user-attachments/assets/b13e61bf-23cf-4b0f-8936-173d1b656640

</details>

### Other helpful information

I do have upwards of 1,000 tracks in my library, if that matters, but the albums never have more than 20-30 tracks.

Nothing useful found in logcat logs containing "player.phonograph.plus".

**Comment by julmey** [comment]
Same here, sometimes I have to tap an album as many as 10+ times to open it, very annoying.


My system:

App version:     1.8.3 (1083)
Git Commit Hash: aad08e40ce94acf73919fce44887951110e0dff5
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 14 (API 34)
Architecture:    arm64-v8a
Soc:             GS201/lynx (by Google) 
Device brand:    google (by Google)
Device model:    lynx/Pixel 7a (code lynx)
Build version:   AP2A.240805.005
                 (12025142)
Language:        de
Screen:          2219x1080 (dpi 420)
Permissions:     Storage(READ WRITE)

**Comment by AntiSol** [comment]
I also see the same behaviour, but for me it's more like 10% of the time it works rather than ~50%. 
It seems like tapping on something else and then tapping again makes it more likely to work.

I also have a large library (about 10,000 songs).

```
App version:     1.8.4 (1084)
Git Commit Hash: ff9861b5a23611e2a02b2b62eebc0f7dbd119bca
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 10 (API 29)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             mt6771/g61v71c2k_dfl_eea 
Device brand:    Unihertz (by A-gold)
Device model:    Titan_EEA/Titan (code Titan)
Build version:   Titan_EEA_20221117
                 (root.20221117.200449)
Language:        en
Memory:          2135/5764 
Screen:          1436x1432 (dpi 400)
Permissions:     Storage(READ WRITE)
```
Happy to provide any other info you think might be useful

**Comment by eku** [comment]
> Happy to provide any other info you think might be useful

Could you please provide an `adb logcat` output of the situation?

**Comment by chr56** [comment]
It should be fixed since commit 70ae349a: [Preview Build](https://github.com/user-attachments/files/17605442/Preview-70ae349a.zip) for test and validation.



@AntiSol @julmey @shibedrill

**Comment by AntiSol** [comment]
I'm hesitant to say it's solved but this is certainly a big improvement. I have not seen the issue on the preview version after clicking into a bunch of albums. As mentioned previously it was happening "most of the time". So while I wouldn't be confident enough to call it "fixed" just yet, it certainly _appears_ to be fixed to me. Thanks!

...though I am now seeing a bunch of other issues on this preview, e.g album art doesn't load nearly as consistently as it used to, many albums are showing no art. Probably not related though I guess?

**Comment by chr56** [comment]
> ... many albums are showing no art.

Default image would be showed **till a candidate album art is fetched** in Album Detail. However, this procedure may be very **long** (it iterates over all songs/files to obtaining embedding artworks), you have to wait patiently (once you have an album with too many songs).

**Comment by chr56** [comment]
On my devices, this bug happened rarely (but not zero possibility, about 1 in 30). 
Now, with the fix, the problem no longer happens on my devices. @AntiSol

**Comment by AntiSol** [comment]
I do have over 10k songs so it is occasionally slow to show album art. but it seems a lot less reliable about that with this update. still it's probably not relevant for this ticket.

yeah for me it was maybe 80% or more of the time and it has not happened with the preview. So that is very promising :+1:

**Comment by chr56** [comment]
[v1.8.5](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.5) has been released! 

This issue _should_ be fixed.
Reopen if it happens again, or create a new one for the similar or newly introduced one.

**Close**!
