### ISSUE TITLE
[Feature Request]Remove built-in updates and networking for f-droid branching

### ISSUE THREAD

**Issue by goddaneel** [chr56/Phonograph_Plus#212]

**Comment by chr56** [comment]
I do not think that is _necessary_, since that would produce more variant dimensions.

**Comment by goddaneel** [comment]
I'm actually more concerned about whether or not more online features will be added later on, as I see that there are some online features in the "more" option.
Honestly I don't really want any online services, there are enough of those kinds of programs out there and usually they don't have time to perfect local playback.

**Comment by chr56** [comment]
1. Any of these "online" features would never cause Internet traffic, _as long as_ you do not use or enable it.
2. I do not have extra energy or time to maintain another variant dimension without these "online" features. So, _help yourself_ (fork it and remove them by yourself, optionally make a PR, this how opensource software works), or do not use it if you really concern.

**Comment by goddaneel** [comment]
I respect your choice, and if this need causes unnecessary stress, then it is an unnecessary feature.
