### ISSUE TITLE
[Bug] The music control panel of the notification bar can't display album art

### ISSUE THREAD

**Issue by 526awd** [chr56/Phonograph_Plus#214]
### Bug Summary

When music is playing, the music control frame of the notification bar cannot display the cover

### Version

1.8.2

### Screenshots or Screen recordings

https://github.com/user-attachments/assets/f6cba573-8622-403f-9bd5-f55d0d3f71b3

**Comment by chr56** [comment]
Consider toggling `Always use Media Session to display cover` (`总是使用 Media Session 显示图片`) in Settings -> Compatibility.

**Comment by 526awd** [comment]
Even if this is turned on, it will not be displayed

**Comment by chr56** [comment]
Fixed in 614e71f8.

Preview Version: [Preview-614e71f8.zip](https://github.com/user-attachments/files/16647128/Preview-614e71f8.zip)

**Comment by chr56** [comment]
[v1.8.3](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.3) has been released, close!
