### ISSUE TITLE
[Crash Report] Crash when creating new playlist from song list

### ISSUE THREAD

**Issue by Radoom** [chr56/Phonograph_Plus#217]
### Crash log

```
Crash Report:

App version:     1.8.3 (1083)
Git Commit Hash: aad08e40ce94acf73919fce44887951110e0dff5
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 12 (API 31)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             Exynos 9820/exynos9820 (by Samsung) 
Device brand:    samsung (by samsung)
Device model:    beyond2lteeea/SM-G973F (code beyond2)
Build version:   BeyondROM 9.1 HVC6
                 (G975FXXUEHVC6)
Language:        de
Screen:          2047x1080 (dpi 420)
Permissions:     Storage(READ WRITE)


Stacktrace:
java.lang.IllegalArgumentException: Failed requirement.
	at ab.k.c(SourceFile:48)
	at j7.b.d(SourceFile:72)
	at kg.v.k(SourceFile:90)
	at kg.t.invokeSuspend(SourceFile:33)
	at g9.a.resumeWith(SourceFile:9)
	at y9.i0.run(SourceFile:92)
	at androidx.recyclerview.widget.w.run(SourceFile:283)
	at fa.k.run(SourceFile:3)
	at fa.a.run(SourceFile:96)
	Suppressed: da.f: [s1{Cancelling}@32515cb, Dispatchers.IO]
```

### Version

1.8.3

### Steps to reproduce the bug

1. Browse your library, i.e. / e.g. by Artist. 
2. Select an artist to see all its songs. 
3. Tap the three-dots in the upper right. 
4. Tap "add to playlist...".  
5. Tap "new playlist". 
6. (Type in playlist name or leave empty for now - does not matter for the next step to trigger the crash). 
7. Tap the "+" icon to select the storage. => App crashes immediately as per above.

However: It does NOT crash if I crate a new playlist from the "playlist" view/tab (and later add songs to it) 

1. Go to "playlists". 
2. Tab the "(+)" in the lower right. 
3. Here, using the "+" icon to browse for the new playlist location does NOT crash. 
4. After a new/empty playlist is created this way, songs can be added to it following steps 1-4 above and then selecting the pre-created empty playlist

### Environment

Android 12

**Comment by chr56** [comment]
Fixed in revision 0a87a420

**Comment by chr56** [comment]
The fix is included in [preview_1.8.4-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.8.4-dev2).

**Comment by chr56** [comment]
[v1.8.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.4) has been released, close!
