### ISSUE TITLE
[Bug] Songs map to wrong album posters

### ISSUE THREAD

**Issue by TTTUUUIII** [chr56/Phonograph_Plus#225]
### Bug Summary

When quickly slide the song list (or song file size is very large), Songs map to wrong album posters.

Phonograph Plus v1.8.4 on Pixel 7 Pro

### Version

1.8.4

### Environment

|HARDWARE|SYSTEM|BRAND|
|--------|---------|--------|
|Pixel 7 Pro|Android 14|Google|

### Screenshots or Screen recordings

<img src="https://github.com/user-attachments/assets/f6245eaa-6fd1-4e20-94cd-2338187f4102" width=30%>

**Comment by eku** [comment]
What are your settings for `Image Cache` and  `Preload Images`? Check if disabling both solves your problem.

**Comment by TTTUUUIII** [comment]
> What are your settings for `Image Cache` and `Preload Images`? Check if disabling both solves your problem.

Thank you for your reply. I tried following your instructions and the situation has improved a lot, but there are still problems with several larger files.

<img src="https://github.com/user-attachments/assets/91e3478a-dd3b-4500-aad9-f67ce6ea3c1a" width=30% />

Settings

<img src="https://github.com/user-attachments/assets/b61e0af7-b6f3-4bc3-a7e5-ec9823880c9c" width=30% />

Songs that still have this problem，I tried reboot app but useless.

The songs are relatively large and I added posters to them using ffmpeg, I'm sure they can display the posters correctly on the PC.

**command**
```shell
# add a poster for audio
ffmpeg.exe -i '.\videoplayback (3).weba' -i '.\maxresdefault (2).jpg' -metadata title="90's Lofi City 🌧️Rainy Lofi Hip Hop 🎶 Lofi Music & Rain Sound" -metadata artist='Cities Vibes' -map 0:a -map 1 -c:v mjpeg -id3v2_version 3 "90's Lofi City 🌧️Rainy Lofi Hip Hop 🎶 Lofi Music & Rain Sounds-Chil Cities Vibesl.mp3"
```

<img src="https://github.com/user-attachments/assets/fc370461-18bd-4f49-9603-6675a30a1949" width=80% />

[Wrong songs occurred.tar.gz](https://proxy.snowland.ink/Wrong%20songs%20occurred.tar.gz)

**Comment by eku** [comment]
> Songs that still have this problem，

Can you provide one of the problematic audio files?

**Comment by TTTUUUIII** [comment]
> > Songs that still have this problem，
> 
> Can you provide one of the problematic audio files?

Of course, But the file size is too large, github does not allow me to upload it in this comment area. Please download use this link [Wrong songs occurred.tar.gz](https://proxy.snowland.ink/Wrong%20songs%20occurred.tar.gz).

**Comment by chr56** [comment]
> Songs that still have this problem

It is similar to [Random Album Artwork](https://github.com/chr56/Phonograph_Plus/blob/v1.8.4/docs/FAQ.md#random-album-artwork), all these files have **_the same album field_** in their tag, resulting in "one album poster".

> So these all audio files are considered as an album, which means any cover artwork of these files are considered as "same" leading random artwork.

We presume that all files with same album tag field has same cover artwork, and any image from any of these files can represent for all.

**Comment by chr56** [comment]
This is "a proper behavior" or `MediaStore`. It would **not** be fixed.

Use other `Image Source` in Settings may fix (no tested yet).

The issue would be _closed_ as planned.

**Comment by TTTUUUIII** [comment]
> This is "a proper behavior" of `MediaStore`. It would **not** be fixed.
> 
> Use other `Image Source` in Settings may fix (no tested yet).
> 
> The issue would be _closed_ as planned.

OK, Thank you for your reply.
