### ISSUE TITLE
[Bug] java.io.UnsupportedEncodingException reading tags for some files

### ISSUE THREAD

**Issue by AntiSol** [chr56/Phonograph_Plus#227]
### Bug Summary

Trying to view/edit id3 tags for certain songs causes the attached exception:

```
Internal Error:

App version:     1.8.4 (1084)
Git Commit Hash: ff9861b5a23611e2a02b2b62eebc0f7dbd119bca
Package name:    player.phonograph.plus
Release favor:   modernStable
Android version: 10 (API 29)
Architecture:    arm64-v8a, armeabi-v7a, armeabi
Soc:             mt6771/g61v71c2k_dfl_eea 
Device brand:    Unihertz (by A-gold)
Device model:    Titan_EEA/Titan (code Titan)
Build version:   Titan_EEA_20221117
                 (root.20221117.200449)
Language:        en
Memory:          2135/5764 
Screen:          1436x1432 (dpi 400)
Permissions:     Storage(READ WRITE)


Note:
Failed to read all tags for /storage/emulated/0/Mp3s/The Glitch Mob - 2018 - See Without Eyes (Deluxe) - 02 - Take Me with You (feat. Arama).mp3

Stacktrace:
java.io.UnsupportedEncodingException
	at md.x.n(SourceFile:3)
	at qf.j.b(SourceFile:231)
	at qf.n.a(SourceFile:11)
	at qf.m.loadSongInfo(SourceFile:121)
	at ch.i1.invokeSuspend(SourceFile:91)
	at r9.a.resumeWith(SourceFile:9)
	at ka.f0.run(SourceFile:102)
	at androidx.recyclerview.widget.u.run(SourceFile:188)
	at ra.j.run(SourceFile:3)
	at ra.a.run(SourceFile:93)
```

### Version

1.8.4

### Steps to reproduce the bug

1. navigate to file 
2. select file
3. choose 'tag editor' in the menu
4. observe error

Note however that it does seem to populate the tag correctly, so I'm not sure what tag it's having trouble with

[file.zip](https://github.com/user-attachments/files/17227301/file.zip)

**Comment by chr56** [comment]
It encounters a very special frame of ID3 Tag: `AggregatedFrame` (`TYERTDAT`), and could not be handled properly.

**Comment by chr56** [comment]
Try this Preview Release: 
[Preview-TagError.zip](https://github.com/user-attachments/files/17228402/Preview-TagError.zip)

**Comment by AntiSol** [comment]
Apologies for the slow reply, you are too fast! ;) I had forgotten that you had replied until just now.

The preview build you attached does indeed solve this problem, thank you!

**Comment by chr56** [comment]
[v1.8.5](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.5) has been released! 

This issue _should_ be fixed.

**Close**! 
Reopen the issue if it happens again, or create a new issue for a similar one or a newly introduced one.
