### ISSUE TITLE
[Bug] lyrics Format Parsing: Plain lyrics with '[' are not displayed.

### ISSUE THREAD

**Issue by DatGizmo** [chr56/Phonograph_Plus#235]
### Bug Summary

If a plain lyric file (non LRC) contains '[' the lyrics will not be displayed.

I'm assuming that the lyrics parser sees the '[' and expects the LRC format.
But I'm using mostly genius to fetch my lyrics and there it is "standard" to use '[' and ']' for non lyric info like '[Intro]'
[Example lyric file](https://genius.com/Ad-infinitum-parasite-lyrics)

The same thing happens if the lyrics are embedded in the audio file.

Personally I would be fine to disable support / parsing for LRC files if the option is disabled.

### Version

1.8.4    (F-Droid  ff9861b5)

### Steps to reproduce the bug

Add a lyrics file which contains '[' at the start of a line.

### Environment

Android 13
LineageOs: 20-20230702-microG

**Comment by chr56** [comment]
This should be improved in c4fe010a.

**Comment by chr56** [comment]
Here is a preview channel build for testing: [Preview-LrcDetection](https://github.com/user-attachments/files/17508165/Preview-LrcDetection.zip)

**Comment by DatGizmo** [comment]
Did a quick test with the preview build, and lyrics are now displayed correctly
Thanks for the quick fix :)

**Comment by chr56** [comment]
[v1.8.5](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.5) has been released! 

This issue _should_ be fixed.

**Close**! 
Reopen the issue if it happens again, or create a new issue for a similar one or a newly introduced one.
