### ISSUE TITLE
[Bug]  Images of App Widget would not be updated after rebooting the device

### ISSUE THREAD

**Issue by Dim7x0** [chr56/Phonograph_Plus#236]
### Bug Summary

Minor issue  - after reboot device, the tag on the widget is not updated
befor 
![WhatsApp Image 2024-10-23 at 09 13 49](https://github.com/user-attachments/assets/cec4033a-f5f0-460a-9ee9-2cd4323deb45)
after tap on tag
![WhatsApp Image 2024-10-23 at 09 13 49 (1)](https://github.com/user-attachments/assets/01df10e7-5371-45ce-a90c-dfd3b1a5d814)

### Version

1.8.4

**Comment by chr56** [comment]
This should be fix in 4891809b: [Preview Build](https://github.com/user-attachments/files/17582149/Preview-4891809b.zip)

**Comment by chr56** [comment]
This should be fix in e63279a1: [Preview Build](https://github.com/user-attachments/files/17582153/Preview-e63279a1.zip)

**Comment by chr56** [comment]
[v1.8.5](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.8.5) has been released! 

This issue _should_ be fixed.

**Close**! 
Reopen the issue if it happens again, or create a new issue for a similar one or a newly introduced one.
