### ISSUE TITLE
[Feature Request] Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [chr56/Phonograph_Plus#244]
We find that there is a `DependencyInfoBlock` in your apk. It's a [Frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the signing block. It's added by AGP and signed by Google's public key so it can't be read by anyone else except Google.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by chr56** [comment]
Done in 8ad3e74d in dev and 1d31b8a6 in main

**Comment by linsui** [comment]
Thanks!

**Comment by chr56** [comment]
Should I make a patch release now?

**Comment by linsui** [comment]
It would be great!

**Comment by linsui** [comment]
Thanks!
