### ISSUE TITLE
[Bug] new audio file not update instantly and auto

### ISSUE THREAD

**Issue by AdityaMishra135** [chr56/Phonograph_Plus#247]
### Bug Summary

After download new audio its not detect instant.It does not happen automatically but it does not show instantly even on manual refresh. Here it shows after restarting the app once or twice.

### Version

Latest

**Comment by chr56** [comment]
Use `Scan Media`, some systems may not notify changes instantly to applications somehow.

**Comment by AdityaMishra135** [comment]
> Use `Scan Media`, some systems may not notify changes instantly to applications somehow.

I have a suggestion, by using media content observer it detects instant changes.in any devices

**Comment by chr56** [comment]
> by using media content observer

Did you mean [MediaStoreObserver](https://github.com/chr56/Phonograph_Plus/blob/e40633fc5d79b8ade20c093a4b4f5a62bb50af24/app/src/main/java/player/phonograph/service/util/MediaStoreObserverUtil.kt#L24)? 

On some devices, it just does not notify applications (moreover, some systems doesn't update MediaStore _at all_ if 
transmission files using connecting desktop computer via MTP).

Nothing can we do. We can not and do not fix System, and we also do not make adaptions for some broken, buggy or weird systems and devices.

**Comment by AdityaMishra135** [comment]
> > by using media content observer
> 
> Did you mean [MediaStoreObserver](https://github.com/chr56/Phonograph_Plus/blob/e40633fc5d79b8ade20c093a4b4f5a62bb50af24/app/src/main/java/player/phonograph/service/util/MediaStoreObserverUtil.kt#L24)? We already use it.
> 
> On some devices, it just does not notify applications (moreover, some systems doesn't update MediaStore _at all_ when transmitting files using connecting desktop computer via MTP).
> 
> Nothing can we do. We can not and do not fix operate systems, and we also do not make adaptions for some broken, buggy or weird systems and devices.

After clean up media observer its working fine, thank you
