### ISSUE TITLE
[Bug Report] Sleep Timer fails, the music is paused after the alarm rings, but cannot continue automatically even after the alarm is turned off

### ISSUE THREAD

**Issue by Ssssspf** [chr56/Phonograph_Plus#26]
更新后出现，睡眠定时失效，闹钟响起后音乐暂停，关闭闹钟后不能自行继续播放。
Device info:
---
<table>
<tr><td>Package name</td><td>player.phonograph.plus</td></tr>
<tr><td>App version</td><td>0.3.1</td></tr>
<tr><td>App version code</td><td>303</td></tr>
<tr><td>Android build version</td><td>cf9b02468f</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>lineage_nio-userdebug 11 RQ3A.211001.001 cf9b02468f</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>nio</td></tr>
<tr><td>Device model</td><td>Motorola Edge S</td></tr>
<tr><td>Device product name</td><td>nio_retcn</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by chr56** [comment]
v1.0.0 makes some changes, it is outdated, please check it again.
v1.0.0 动了一下“相关机制”，请确定知否还能复现.
