### ISSUE TITLE
[Bug Report] Enqueue folder: no longer recursive

### ISSUE THREAD

**Issue by maemunman** [chr56/Phonograph_Plus#29]
**Describe the bug or unexpected behavior**
I used to be able to enqueue a folder and have all songs in that directory and in all subdirectories therein added to the queue recursively. This doesn't happen for anymore. Rather, when I enqueue a folder, only the top level audio files are added to queue.

**Crash log**
n/a

**How to reproduce**
Steps to reproduce the bugs or unexpected behaviors:

1) find a directory in the files tab: one with subdirectories and songs in those subdirectories
2) select that folder and add it to queue
3) none of the subdirectories contents are enqueued 

**Screenshots (Optional)**
(if available)

**Other information**
…

**Comment by chr56** [comment]
**Confirmed.** It would be fixed in next version(s) if possible.

**Comment by chr56** [comment]
Fixed in commit [`f3d081859639e`](https://github.com/chr56/Phonograph_Plus/commit/f3d081859639e167aaa375757fd2e298f77333c9)

**Comment by chr56** [comment]
[Phonograph Plus Preview Version](https://github.com/chr56/Phonograph_Plus/files/9623582/previewRelease.zip)

For test

**Comment by maemunman** [comment]
It seems to work! Thank you

**Comment by chr56** [comment]
close! 
fixed in [v0.3.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.3.4)
