### ISSUE TITLE
Ability to play single files

### ISSUE THREAD

**Issue by elesto** [chr56/Phonograph_Plus#33]
Hello, could you add a way to disable the automatic starting of a playlist when you click just one file. I want to just play one song and stop.

**Comment by chr56** [comment]
Excuse me, I can not understand what specific features you ask? Can you describe the "precise" behavior about them?

**Comment by uli-on** [comment]
@elesto What you ask can be achieved by starting the track via a file manager's Open With.

**Comment by elesto** [comment]
Yes, thank you.
I prefer to use the audio players folder view since it displays thumbnails. 
I suggest: add a toggle to folder view which disables the automatic adding of all the other songs in the folder to the playlist when I choose just one song.

**Comment by uli-on** [comment]
@elesto Can you make use of emptying the queue and subsequently tapping the desired track?

**Comment by elesto** [comment]
@uli-on Yes, but tapping the track just adds the entire folders contents to the que

**Comment by uli-on** [comment]
Hm. What might I be doing differently? Have you emptied the queue completely and opened i.e. tapped the album?

**Comment by uli-on** [comment]
Ah wait, I don't use the folder tree tab.

**Comment by uli-on** [comment]
Nope, same behaviour in folder tree view as before: Clear queue, tap song, tap play, gives one song in thevqueue.

**Comment by chr56** [comment]
[Preview v0.5-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.5-dev1) is available now.

`Custom behavior when clicking a song` _**would**_ be what you request.

Go to `Custom behavior when clicking a song` in setting, then checking `Repeat this song only`  and uncheck `If current queue is empty, play the queue directly`, then every song you click would be "single-played".

**Comment by chr56** [comment]
It's been almost half a year. I am not sure whether you are satisfied or not, but I am planning to close this anyway.

This issue would be closed on May 1.

**Comment by chr56** [comment]
May 1, Close!
