### ISSUE TITLE
[Suggestion] provide compilation instructions

### ISSUE THREAD

**Issue by fislysandi** [chr56/Phonograph_Plus#39]
i would like to see how to compile phonograph plus instructions for this fork (even better if you provide the instructions how to compile it on termux.)

i would really appreciate that 

and thank you for this fork.

**Comment by chr56** [comment]
On `Termux`?  I am not sure if it is possible. `JDK ` 11 and `gradle`(`gradlew`) must **at least** be required. I am not sure they are available on Android.

But I can write instructions for X86 PC.

**Comment by fislysandi** [comment]
thank you mate.

**Comment by chr56** [comment]
Here:
[Build_Instructions.md](https://github.com/chr56/Phonograph_Plus/blob/dev/Build_Instructions.md#instructions-build-with-commandline)
Written in a hurry, not well detailed, just a normal Android build routine, nothing special (except the custom `Build Variant`)

**Comment by fislysandi** [comment]
i will just close this issue because its stale and resolved.
