### ISSUE TITLE
[Bug Report]Error reading not found Lyrics

### ISSUE THREAD

**Issue by XMA2l** [chr56/Phonograph_Plus#42]
**Describe the bug or unexpected behavior**
Exception/crash report on each app startup

**Crash log**
If app crashed, copy the logs if available.
```
Crash Report:

Package name:    player.phonograph.plus
App version:     0.4.0 (400)
Git Commit Hash: 2fdd1d6c262556de0ff8
Android version: 12 (SDK 32)

Failed to read lyrics from song

java.io.FileNotFoundException: Unable to find:/storage/emulated/0/DirToMyMusic/MySong.mp3
	at i8.b.a(SourceFile:155)
	at ja.c.a(Unknown Source:3)
	at ja.c$c.invokeSuspend(Unknown Source:12)
	at e6.a.resumeWith(Unknown Source:8)
	at u6.o0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:66)
}

```

**Other information**
…
I dont think the mp3 is corrupt, it plays fine, but i moved a lot of files recently before this error occured!

**Comment by chr56** [comment]
It seems that error occurs when reading embed lyrics.

Please check **permissions** of Phonograph Plus. 
And try to grant **FULL** file access permission (like `Manage external storage` or `Allow management of all files`).

I would check the code soon  as soon as possible, try not to play this song now.

**Comment by chr56** [comment]
_If you are still using Phonograph Plus, please read:_


This might be a problem of Android Permission.

You can **grant** fully storage permission to mute this as well.

This notification is muted since bf4a3321a03c39a6158d967f33f180c4bdb34597;

**Comment by chr56** [comment]
_If you are still using Phonograph Plus, please read:_

This notification should be muted since [v1.3.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.3.0).

Please grant full storage access permission if you really have local lyrics. (`Main Drawer Menu -> More -> Grant External Storage Permission` will guide you)

Close!

**Comment by XMA2l** [comment]
Thx a lot :)
