### ISSUE TITLE
[Feature Request] empty queue with button or on close.

### ISSUE THREAD

**Issue by firefoxlover** [chr56/Phonograph_Plus#44]
If you use folders for your playlists, it is nessecary for using them like playlists, to be able to

1. Add the folder to the queue (with shuffle?)
2. Clear the qeue again to play another playlist

Thanks for this great app!

**Comment by chr56** [comment]
[Preview v0.5-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.5-dev1) is available now.

`Custom behavior when clicking a song` may help you.

Go to `Custom behavior when clicking a song` in setting, check the radio button starting with `Replace the current,`, this may be what you want.

**Comment by chr56** [comment]
It's been almost half a year. I am not sure whether you are satisfied or not, but I am planning to close this anyway.

This issue would closed on May 1.

**Comment by firefoxlover** [comment]
sorry for not responding. I can check again. In general I think the worst of all the music apps is that they have their own playlist formats. So having folder structures is just the simplest, even though not the best of course.

**Comment by chr56** [comment]
May 1, Close!
