### ISSUE TITLE
[Feature request] Audio keep on playing after interruption

### ISSUE THREAD

**Issue by firefoxlover** [chr56/Phonograph_Plus#45]
Navigation apps like OSMAnd interrupt audio playback if you set it like that.

But when the music is paused, it doesnt keep on autoplaying. 

This is an integrateable feature, Retro Music player has it.

**Comment by chr56** [comment]
This would be kind of tricky, and I am busy thesedays.
So please wait patiently.

**Comment by chr56** [comment]
[v1.0.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.0) has released, please turn on in Setting! Close!
