### ISSUE TITLE
[Bug]: Can not change grid size of lists on large tablet devices

### ISSUE THREAD

**Issue by Bejukoro** [chr56/Phonograph_Plus#46]
### Bug Summary

平板设备上，横屏时歌曲列表的网格尺寸被固定在6，无法修改
选择其它网格尺寸时不会生效，尺寸依然是6
（在手机上横屏时未发现此问题，可以正常修改网格尺寸）

### Version

0.4.1

### Screenshots or Screen recordings

![Screenshot_20221113-091707_Phonograph Plus](https://user-images.githubusercontent.com/42836326/201501066-9c00ba93-82ec-4348-be58-2e067ab6aaa1.png)
![Screenshot_20221113-091715_Phonograph Plus](https://user-images.githubusercontent.com/42836326/201501080-1e2c505f-79dc-45b6-a29d-3c14bdbed1e7.png)

### Environment

Mi Pad 5 (nabu)
ArrowOS 13.0 (Android 13)

**Comment by chr56** [comment]
？？？

可以的话，把设置导出，然后把json内容发出来看看

**Comment by Bejukoro** [comment]
> ？？？
> 
> 可以的话，把设置导出，然后把json内容发出来看看

`{
  "fixed_tab_layout": false,
  "SHUFFLE_MODE": 1,
  "classic_notification": false,
  "last_added_interval": "past_seven_days",
  "REPEAT_MODE": 0,
  "broadcast_current_player_state": true,
  "use_legacy_list_files_impl": false,
  "POSITION": 0,
  "should_color_app_shortcuts": true,
  "synchronized_lyrics_send": true,
  "use_legacy_favorite_playlist_impl": false,
  "last_start_page": 0,
  "general_theme": "auto",
  "ignore_media_store_artwork": true,
  "remember_shuffle": true,
  "remember_last_tab": true,
  "blurred_album_art": false,
  "album_art_on_lockscreen": true,
  "keep_playing_queue_intact": true,
  "POSITION_IN_TRACK": 65351,
  "synchronized_lyrics_show": true,
  "audio_ducking": true,
  "check_upgrade_at_startup": true,
  "colored_notification": true,
  "playlist_files_operation_behaviour": "auto",
  "auto_download_images_policy": "never",
  "intro_shown": true,
  "song_sort_mode": "song_name:0",
  "use_legacy_detail_dialog": false,
  "enable_lyrics": true,
  "song_grid_size": 2,
  "gapless_playback": false,
  "song_colored_footers": true,
  "display_lyrics_time_axis": true,
  "initialized_blacklist": true,
  "last_changelog_version": 401
}`

**Comment by Bejukoro** [comment]
> ？？？
> 
> 可以的话，把设置导出，然后把json内容发出来看看

对比了在手机上导出的 json 文件后，我在平板上导出的 json 文件中加上了 `"song_grid_size_land": 3` 这一行，然后导入回应用中。
此时横屏时的网格尺寸成功变成了 3，但是依然无法通过对应选项进行修改，选择其他选项后横屏网格尺寸也会保持在 3。

**Comment by chr56** [comment]
> 对比了在手机上导出的 json 文件后，我在平板上导出的 json 文件中加上了 `"song_grid_size_land": 3` 这一行，然后导入回应用中。 此时横屏时的网格尺寸成功变成了 3，但是依然无法通过对应选项进行修改，选择其他选项后横屏网格尺寸也会保持在 3。

那么，就是新设置保存不了，可能是UI问题，保存不了新值，但是就只在平板出现，就挺诡异。

等我再检查一下源码...

**Comment by chr56** [comment]
问题已在模拟器上复现，应该是平板(sw600dp,短边大于600dp设备)特有的. @Bejukoro

**Comment by chr56** [comment]
已于 db758a0e7 修复

**Comment by chr56** [comment]
`Preview` 通道:  (包名`player.phonograph.plus.preview`)
[Phonograph_Plus_0.5_dev1_db758a0e7.zip](https://github.com/chr56/Phonograph_Plus/files/9996466/previewRelease.zip)


@Bejukoro 你再试试这个

**Comment by Bejukoro** [comment]
> `Preview` 通道: (包名`player.phonograph.plus.preview`) [Phonograph_Plus_0.5_dev1_db758a0e7.zip](https://github.com/chr56/Phonograph_Plus/files/9996466/previewRelease.zip)
> 
> @Bejukoro 你再试试这个

已修复，感谢 👍

**Comment by chr56** [comment]
如果顺利的话，0.5.0应该能在这个月发布

**Comment by chr56** [comment]
> 已修复，感谢 👍

如果顺利的话，0.5.0应该能在这个月发布

**Comment by Bejukoro** [comment]
> > 已修复，感谢 👍
> 
> 如果顺利的话，0.5.0应该能在这个月发布

辛苦了 🙆

**Comment by chr56** [comment]
Closed, due to release of [v0.5.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.0)
