### ISSUE TITLE
[Feature Request] Setting to sort by Album Artist 

### ISSUE THREAD

**Issue by verbophobia** [chr56/Phonograph_Plus#50]
Perhaps in settings have a selection to change default sorting of artist to album artist. This will help for those of us with multiple compilations.

**Comment by chr56** [comment]
Almost done, 1d3890bdaf9f7d3bd4c.

Now, on Android R (11) and above, there's a new sort order -- "_album artist_" for Song. And album's 'artist' field would be from tag _album artist_, or tag _artist_ if album artist is empty.

Test Preview Version: [ALBUM_ARTIST.zip](https://github.com/chr56/Phonograph_Plus/files/10285051/ALBUM_ARTIST.zip)

**Comment by chr56** [comment]
Well, it's been half a year. I do not know whether you still use this or not.
But this feature is finally merged now: [preview_0.7.0-dev4](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.7.0-dev4).

**Comment by chr56** [comment]
[v0.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.7.0) has released now. Close!
