### ISSUE TITLE
Working with the music library

### ISSUE THREAD

**Issue by userkilled** [chr56/Phonograph_Plus#53]
The application scans 4 objects from X and freezes. There is no further action in the notification.
To rescan, you have to reset the application data.

**Comment by chr56** [comment]
excuse me, what is "X and freezes"?

**Comment by userkilled** [comment]
I say files. 'X' is other number

**Comment by userkilled** [comment]
![Screenshot](https://user-images.githubusercontent.com/39238592/210193731-d22873bf-cfd1-49f6-8f9b-ce2f8417f6f1.png)

**Comment by chr56** [comment]
_(if you are still use Phonograph Plus)_

[v1.4.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.4.0) is released!

Scanning is improved now.

**Comment by userkilled** [comment]
Great
