### ISSUE TITLE
[Bug]: Failed to read lyrics from song.

### ISSUE THREAD

**Issue by Gh0stz0x** [chr56/Phonograph_Plus#54]
### Bug Summary

The application has an internal error when it can't find the lyric.

### Version

0.5.3

### Steps to reproduce the bug

To reproduce the problem, it is sufficient that there is a song without a lyric.

### Environment

Android version: 10 (SDK 29)
Device brand:    HUAWEI  (by HUAWEI)
Device model:    HMA-L29 (code: HWHMA)
Product name:    HMA-L29
Build version:   HMA-L29 10.1.0.288(C55E8R1P5) 
                 (10.1.0.288C55)
Hardware:        kirin980
Language:        it

### Other helpful information

Internal Error:

Package name:    player.phonograph.plus
App version:     0.5.3 (453)
Git Commit Hash: aa473d795af5080412ba

Failed to read lyrics from song

java.io.FileNotFoundException: Unable to find:/storage/emulated/0/Music/My Chemical Romance - I Don_t Love You [Official Music Video] [HD].opus
	at o8.b.a(SourceFile:155)
	at sa.f.a(Unknown Source:3)
	at sa.f$c.invokeSuspend(Unknown Source:12)
	at j6.a.resumeWith(Unknown Source:8)
	at a7.s0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:66)
}

I will do further tests to see when it occurs precisely. 🤔

**Comment by chr56** [comment]
I am not sure. 
It looks like permission error, but it can also can be a bug exsiting (see #9, can not process opus files).

I might mute this message.

**Comment by chr56** [comment]
Opus format should be supported since [v0.5.4](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.4).

This error message _should not_ be showed now.

Ready for closing.
