### ISSUE TITLE
Search the Queue [Feature Request]

### ISSUE THREAD

**Issue by anaskaejdar** [chr56/Phonograph_Plus#56]
Sometimes I want to search the queue. In those times, there are technically other ways to accomplish what I want, but this would seem most simple.

**Comment by chr56** [comment]
Since 59ee66550fc8e8b2b8db902de33a16231fbe1e17, songs in playing queue and playlists can be searched from (Global) Search.

**Comment by chr56** [comment]
[v1.0.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.0) has released! 
Although it is not very perfect now.
Close!
