### ISSUE TITLE
[Bug]: Artwork in player notification does not display in correct aspect ratio

### ISSUE THREAD

**Issue by aorinngoDo** [chr56/Phonograph_Plus#57]
### Bug Summary

In the Player Notification Screen, the artwork is displayed as a vertical rectangle even for files with square artwork

### Version

0.5.4

### Screenshots or Screen recordings

- Incorrect aspect ratio artwork on Player Notification
![Screenshot_20230128-213217_Phonograph_Plus](https://user-images.githubusercontent.com/90427309/215267102-a7c6d1a2-cd5d-4bc7-ab6d-7fadcc7bf6f2.png)

- Correct aspect ratio artwork on Now Playing Screen
![Screenshot_20230128-213150_Phonograph_Plus](https://user-images.githubusercontent.com/90427309/215267099-6df7475f-168c-4709-b389-e82664303750.png)

- Correct aspect ratio artwork on Album Screen
![Screenshot_20230128-213116_Phonograph_Plus](https://user-images.githubusercontent.com/90427309/215267101-a70eae68-42a9-4ed7-abd8-30f491cf8793.png)

### Environment

Screenshots: Android 11 (LineageOS 18.1) / Redmi K40
All application settings are default.
The same behavior was confirmed for Android 13. (Player Notification style is different)

### Other helpful information

Tested with [this silent audio file](https://github.com/chr56/Phonograph_Plus/files/10527301/sample_audio.zip)

**Comment by chr56** [comment]
Confirmed

**Comment by Quintus19** [comment]
This happened with me aswell. (OneUI 3.1, Android 11)

I found out disabling "Show album cover" option under Lockscreen settings fixes it.
![Screenshot_20230423-113647_Phonograph Plus](https://user-images.githubusercontent.com/119014876/233829174-cc26ba0b-505f-4a23-92e4-7ce79fdafbda.jpg)

**Comment by aorinngoDo** [comment]
Confirmed that this issue has been fixed in the latest release, thank you.

**Comment by chr56** [comment]
Yes, @Quintus19. 
Feature `Show album cover in Lockscreen` has confliction with proper Media Notification Artwork.

This is temporarily fixed in [v0.6.2.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.6.2.1). 

And, `Show album cover in Lockscreen` would be _removed_ in next releases. This should be the job of system, instead of applications. (Anyway, it doesn't work on "the modern Androids" now!)
