### ISSUE TITLE
[Bug] Failed to read lyrics from song: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by ahmedfamhy3** [chr56/Phonograph_Plus#58]
### Bug Summary

Internal Error:

Package name:    player.phonograph.plus
App version:     0.5.4 (454)
Git Commit Hash: 52f6af7552aa0d623bf1
Android version: 12 (SDK 32)
Device brand:    POCO  (by Xiaomi)
Device model:    M2012K11AG (code: alioth)
Product name:    lineage_alioth
Build version:   lineage_alioth-userdebug 12 SQ3A.220705.004 ab0a6cffb1 
                 (ab0a6cffb1)
Hardware:        qcom
Language:        en

Failed to read lyrics from song

java.io.FileNotFoundException: Unable to find:/storage/emulated/0/Music/Red_Wings__Aces_of_the_Sky__Original_Soundtrack_/Into_the_Storm.mp3
	at q8.b.a(SourceFile:157)
	at wa.g.a(Unknown Source:3)
	at wa.g$c.invokeSuspend(Unknown Source:12)
	at k6.a.resumeWith(Unknown Source:8)
	at b7.r0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:66)
}

### Version

Latest

### Steps to reproduce the bug

I just open the app

### Environment

Android 12, LineageOS 19.1 Alioth

**Comment by chr56** [comment]
Fix in [v0.5.4.1](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.5.4.1)

**Comment by ahmedfamhy3** [comment]
No it's still
Internal Error:

Package name:    player.phonograph.plus
App version:     0.5.4.1 (454)
Git Commit Hash: 121a4b440d10ed7d2321
Android version: 12 (SDK 32)
Device brand:    POCO  (by Xiaomi)
Device model:    M2012K11AG (code: alioth)
Product name:    lineage_alioth
Build version:   lineage_alioth-userdebug 12 SQ3A.220705.004 ab0a6cffb1 
                 (ab0a6cffb1)
Hardware:        qcom
Language:        en

Failed to read lyrics from song

java.io.FileNotFoundException: Unable to find:/storage/emulated/0/Music/Red_Wings__Aces_of_the_Sky__Original_Soundtrack_/Into_the_Storm.mp3
	at q8.b.a(SourceFile:157)
	at sa.g.a(Unknown Source:3)
	at sa.g$c.invokeSuspend(Unknown Source:12)
	at k6.a.resumeWith(Unknown Source:8)
	at b7.r0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.i.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:66)
}

**Comment by chr56** [comment]
This notification is muted since aadb8ecf94d89f3c304aad8fd58ca8f1cc102fa9;

You can turn off Lyrics Functions or **Grant** fully storage permission to mute this as well.

**Comment by chr56** [comment]
This notification should be muted since [v1.3.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.3.0).

Please grant full storage access permission if you really have local lyrics. (`Main Drawer Menu -> More -> Grant External Storage Permission` will guide you)

Close!
