### ISSUE TITLE
[Bug] Song Detail / Tag Editor freezes when using dark primary colors

### ISSUE THREAD

**Issue by tactical-snail** [chr56/Phonograph_Plus#66]
It works fine when using light primary colors, for example #616161 works but #424242 freezes the app when you open the tag editor. 

And reopening the app doesn't fix it, you have to force stop phonograph plus and then open it.

I don't know the cause but I noticed that the tag editor always uses light colors from the album art for it's ui, so I guess it could be releated to that.

**Comment by uli-on** [comment]
Good find! Same here, also for the Details screen.

**Comment by chr56** [comment]
Sorry, I _can not_ reproduce this.

**Comment by tactical-snail** [comment]
@chr56 Is it device specific then? I'm using a xiaomi with 4gb ram and snapdragon 625, it's running de-googled android 12L. But I also tried on a different device with google services, the same issue occured there.

**Comment by uli-on** [comment]
Android 10 here, Fairphone flavour
Google Play Services v22.36.16 (100408-476895098) [223616030]
OpenGL ES version 3.2

**Comment by chr56** [comment]
Tag Editor and Song Detail are refractored after v1.2.0.

Now, can you still reproduce this?

**Comment by uli-on** [comment]
I can still reproduce both freezes, with the tag editor and with the details screen. Sorry.

**Comment by chr56** [comment]
Theme engine has been refractor in v1.7-dev2.

Now, can you still reproduce this in [v1.7-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.7-dev2)?

**Comment by tactical-snail** [comment]
It works fine now! Thanks.

**Comment by chr56** [comment]
[v1.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.7.0) released. Close!
