### ISSUE TITLE
applicationId changed?

### ISSUE THREAD

**Issue by IzzySoft** [chr56/Phonograph_Plus#68]
### Bug Summary

Looks like you've changed the applicationId. This makes updates impossible, as Android considers it a completely different app now.

### Version

0.6.0.1

### Steps to reproduce the bug

Download the latest APK (versionCode 510) from Github releases, install it on your device, end up with a new app instead of the installed one being updated.

### Other helpful information

The original applicationId was `player.phonograph.plus`, now it is `player.phonograph.plus.preview`. The suffix suggests that it's not final, but there are no pointers so it comes unexpected. If the intention was to give a preview, and the final will have its original applicationId restored, maybe label the corresponding releases as `pre-release`? Github offers that, it's just a check-box to tick :wink:

**Comment by chr56** [comment]
No really, `player.phonograph.plus.preview` is just for Preview Release (labelled with `Pre-release`, you can download one to valid). However, just **by mistake** this "Preview Release" was built and uploaded yesterday, now the correct artifact (`player.phonograph.plus`) was uploaded and replaced with previous one. 

Sorry for inconvenience, this is just a mistake.

**Comment by IzzySoft** [comment]
No problem, mistakes happen – and thanks for clarification! Then my updater will find and pick the correct APK on its next run in about an hour.
