### ISSUE TITLE
[Bug]: color correction

### ISSUE THREAD

**Issue by heberjeur** [chr56/Phonograph_Plus#72]
### Bug Summary

OK and cancel color belongs to accent not to primary setting

![Screenshot_20230319-093834_Phonograph Plus](https://user-images.githubusercontent.com/11852634/226163490-4bb35261-72fd-484d-8a40-6f9f9a89a2e6.jpg)

### Version

0.6.0.1

**Comment by chr56** [comment]
Yes, it is.

**Comment by chr56** [comment]
[v0.6.2](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.6.2) is released now! 


Close!
