### ISSUE TITLE
More tags in editor [Feature Request]

### ISSUE THREAD

**Issue by anaskaejdar** [chr56/Phonograph_Plus#73]
I'd like to be able to edit the lyrics tag. It would also be good to add more tag fields than offered by default, for any possible tag fields; for example,

![Screenshot_۲۰۲۳۰۳۲۱_۰۸۳۴۱۵_Tag Editor](https://user-images.githubusercontent.com/32847759/226658103-74400cbd-7986-46a5-8ff3-b679d071b3bf.jpg)

The list of possible tags is very long; far longer than this screenshot.

**Comment by chr56** [comment]
This might be postponed till end of this year or even 2024.

**Comment by chr56** [comment]
_This feature is implementing._

In [preview_1.1-dev2](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.1-dev2), all tags defined (currently focusing formats of `ID3v2` for `MPEG Layer-3`(mp3) and metadata in `MPEG-4 Part 14`(mp4/m4a) and `VorbisComment` for flac/ogg ) can be read (only text tags, binary tags like images can not be viewed now right now).

 Writing may be implemented very soon.

**Comment by chr56** [comment]
In [preview_1.1-dev3](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_1.1-dev3), Writing "most common" tags are done.

**Comment by chr56** [comment]
[v1.1.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.1.0) released!

**Comment by chr56** [comment]
The development is almost done since v1.1.0, and this issue is no longer active, Close!
