### ISSUE TITLE
[Bug]: When swiping up or down, it's easy to trigger switching between library category tabs

### ISSUE THREAD

**Issue by chwt163** [chr56/Phonograph_Plus#76]
### Bug Summary

When swiping up or down, it's easy to trigger switching between library category tabs

### Version

0.6.1

huawei Phone: HONOR BKL-AL20(BKL-AL20)
CPU ABI: arm64-v8a
Android Version: 10 API29

**Comment by chr56** [comment]
Seriously? Is this called a bug? And how could you let a gesture requiring vertical scrolling, by mistake, be detected as a gesture requiring horizontal scrolling? By 45° angle scrolling? That is not my problem; it's yours! Thanks!:)

**Comment by chwt163** [comment]
It's not a bug, but it's a minor nuisance. 
VinylMusicPlayer is another fork of Phonograph's music software, you can compare Vinyl's up and down swipe, off a certain angle, Vinyl does not recognize up and down sliding as left and right sliding. 
Many people want to not need the precise operation like FPS games, but can easily operate the software
