### ISSUE TITLE
[Bug]: Non-square artwork does not display in correct aspect ratio

### ISSUE THREAD

**Issue by aorinngoDo** [chr56/Phonograph_Plus#82]
### Bug Summary

When playing a music file has non-square artwork, it is displayed in a square with a different ratio.

The original phonograph (kabouzeid/Phonograph) displays artwork cropped into a square

### Version

0.6.2.1

### Steps to reproduce the bug

Play [this silent audio file](https://github.com/chr56/Phonograph_Plus/files/11304157/sample.zip) with Phonograph Plus.
Its artwork appears in strange square.

### Screenshots or Screen recordings

- Correct aspect ratio (Windows Mp3tag)

  ![image](https://user-images.githubusercontent.com/90427309/233850289-e36076c6-4087-4692-ba78-971bcea6fd41.png)

- Incorrect aspect ratio (Phonograph Plus)
  
  ![image](https://user-images.githubusercontent.com/90427309/233850320-e09f7ded-32fd-4ee8-bea8-f20693817207.png)

- Cropped square (Original Phonograph)
  
  ![image](https://user-images.githubusercontent.com/90427309/233850336-c5b6b13d-47c9-44e0-a8d9-9b5353a58ad3.png)

### Environment

Android 11 (LineageOS 18.1) / Redmi K40
All application settings are default.
The same behavior was confirmed for Android 13 (LineageOS 20).

**Comment by chr56** [comment]
Fixed in 2aa971148ed6413828d08284de1f7ce96678a785

Preview Channel Artifact to test: [RreviewRelease.zip](https://github.com/chr56/Phonograph_Plus/files/11358648/RreviewRelease.zip)
Sample Audio File:  [test_sample.zip](https://github.com/chr56/Phonograph_Plus/files/11358649/test_sample.zip)

**Comment by aorinngoDo** [comment]
Thanks a lot. It works well !
