### ISSUE TITLE
[Feature Request] Support LRC lyric file format

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [chr56/Phonograph_Plus#83]
It would be awesome to have support for LRC file format on interface.

See: https://en.wikipedia.org/wiki/LRC_(file_format)

**Comment by KrasnayaPloshchad** [comment]
Oh, feel free to do so, but I prefers adding some options for this.

**Comment by chr56** [comment]
In [preview_0.7.0-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.7.0-dev1), lyrics can be manually loaded.

**Comment by spectra80** [comment]
How to manually load the lyrics I have tried but I can't manually select the LRC file therefore sometimes the app doesn't recognize the LRC files

**Comment by chr56** [comment]
![Screenshot_20230526-101238](https://github.com/chr56/Phonograph_Plus/assets/30681738/6e6b7e47-5578-4dfa-96b3-cfaa99d00fd7)

Player's menu -> `Choose Lyrics...`

**Comment by chr56** [comment]
Also, make sure the Lrc/Txt Lyrics filename is same with song filename (besides suffix). And full storage access is granted.

**Comment by chr56** [comment]
[v0.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.7.0) has released now.
