### ISSUE TITLE
[Bug]: Colors on Now Playing screen don't update

### ISSUE THREAD

**Issue by Quintus19** [chr56/Phonograph_Plus#84]
### Bug Summary

Let's say you are playing Song A. Song A's cover is mostly blue, therefore the color is blue.
You lock the screen and the song plays in the background. Song A is done and the app skips to the next song, Song B. Song B's cover is mostly red, therefore the color is red.
You unlock the phone and see that the color is blue and didn't update.

Aside from navigation bar and status bar. They do update.

### Version

0.6.3

### Steps to reproduce the bug

0: Make sure the colors of both songs are different enough

1: Play Song A

2: Lock phone

3: Skip to Song B or wait for A to finish

4: Unlock phone

5: Witness the bug

### Screenshots or Screen recordings

![Screenshot_20230504-234540_Phonograph Plus](https://user-images.githubusercontent.com/119014876/236325332-d15c2aca-a671-4244-9b74-6db2ae18c896.jpg)

### Environment

OneUI 3.1, Android 11

**Comment by chr56** [comment]
In [preview_0.7.0-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.7.0-dev1), this problem has almost fixed (unless you switching too quickly)

**Comment by chr56** [comment]
Stable [v0.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.7.0) should not have such problems now.
