### ISSUE TITLE
[Feature Request] Setting to default "Files" tab to [SD Card -> Music] instead of [Internal Storage -> Music]

### ISSUE THREAD

**Issue by therealdrl** [chr56/Phonograph_Plus#87]
Each time I open the app, the files tab reverts to the default internal music folder. I'd like to be able to set the default folder for Files to SD Card, as I store my music there after a broken phone incident.

**Comment by chr56** [comment]
Wait, can `Set as start directory` not satisfy your request?
Just go to your SD Card root, and choose 3-dots-menu of "Music", click `Set as start directory`.
