### ISSUE TITLE
[Bug]: Bunch of error notifications popping up upon entering settings

### ISSUE THREAD

**Issue by Quintus19** [chr56/Phonograph_Plus#89]
### Bug Summary

Whenever I enter settings these error messages pop up. I'm on dev3 right now and the same issue was in dev2 aswell. I tried clearing cache and data, updating from dev2 to dev3, fresh install of dev3 but none of them worked.

### Version

0.7.0-dev3

### Steps to reproduce the bug

1: Launch Phonograph Plus Preview

2: Open "Settings"

### Screenshots or Screen recordings

Here is a screenshot of the error messages on a fresh install of dev3.

![Screenshot_20230612-193901_Phonograph Plus Preview](https://github.com/chr56/Phonograph_Plus/assets/119014876/7ee39675-303f-4c5e-ac67-78aa710ca83a)

### Environment

OneUI 3.1, Android 11

**Comment by chr56** [comment]
That's a bug.
The temporary fix/workaround is:
Set these preferences (`General Theme`, `Last added playlist interval`, `Auto download metadata`, `Operational Behaviour for playlist files`) to _any value_ (yes, any value, even same with the previous or default) for _for once_.

**Comment by chr56** [comment]
Fixed in [preview_0.7.0-dev4](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.7.0-dev4).

**Comment by chr56** [comment]
Stable [v0.7.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.7.0) should not have such problems now.
