### ISSUE TITLE
[Feature Request] Add quickscroll indicator to playing queue

### ISSUE THREAD

**Issue by JonnyVR1** [chr56/Phonograph_Plus#92]
Add a scroll indicator to the playing queue to quickly be able to scroll long lists

**Comment by chr56** [comment]
[preview_0.8-dev1](https://github.com/chr56/Phonograph_Plus/releases/tag/preview_0.8-dev1) has released! 

Scrollbar has added to Playing Queue since `preview_0.8-dev1`, ~though it may be conflicting with gestures of player panel~.

**Comment by chr56** [comment]
[v1.0.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.0) has released! Close!
