### ISSUE TITLE
[Bug]: App crashes when playing an unlisted file

### ISSUE THREAD

**Issue by rohanfw** [chr56/Phonograph_Plus#96]
### Bug Summary

To Replicate:

1) Switch the player to Folders Include Mode in settings, refresh the app
2) Open a audio file not listed in the folders listed in the Include mode in the file manager
3) Try opening the file using Phonograph

The app crashes and won't be able to run any more unless we go to the settings and force close it or use the on screen clear button that will wipe the entire app's data.

### Version

0.7.1

### Steps to reproduce the bug

1) Switch the player to Folders Include Mode in settings, refresh the app
2) Open a audio file not listed in the folders listed in the Include mode in the file manager
3) Try opening the file using Phonograph

**Comment by chr56** [comment]
Fixed since bc9c901f7d09a74ae85d34dc8e0927100c8733b9

**Comment by chr56** [comment]
Fixed in both [v0.7.2.3(lts)](https://github.com/chr56/Phonograph_Plus/releases/tag/v0.7.2.3) and [v1.0.0](https://github.com/chr56/Phonograph_Plus/releases/tag/v1.0.0)! Close!
