### ISSUE TITLE
[Bug]: Playback Issue Caused by Battery Optimisation Setting

### ISSUE THREAD

**Issue by alphanerdgen** [chr56/Phonograph_Plus#97]
### Bug Summary

The app fails to play the next song in the queue if Battery Optimisation is set to 'Optimised' and the app itself has been pushed to the background. No such issue when the same setting has been changed to 'Unrestricted'.

The 'Optimised' setting works for most apps in my phone including Vinyl Music Player (another Phonograph fork) so it's a bit strange that Phonograph Plus needs unrestricted battery usage. Please look into it because I'm afraid that unrestricted usage might cause increased battery drain.

Android: 12

### Version

0.7.1 [F-Droid]

### Environment

Android 12.

**Comment by alphanerdgen** [comment]
@chr56 I'm no longer facing this issue after updating the app to version 1.0.0 from F-Droid today so I'm closing this.

**Comment by chr56** [comment]
Yeah, see changelog: `Modify: disallow canceling media notification when paused(to avoid getting killed)`

@alphanerdgen
